### ISSUE TITLE
Backport IPv4 reassembly to v1.1

### ISSUE THREAD

**Issue by andywingo** [Igalia/snabbswitch#103]
See https://github.com/Igalia/snabbswitch/pull/87

**Comment by andywingo** [comment]
Actually many of the PRs associated with this milestone are relevant: https://github.com/Igalia/snabbswitch/pulls?q=milestone%3Av1.1+is%3Apr

**Comment by aperezdc** [comment]
In PR #116 we have now a working implementation backported from `lwaftr_olive`. I need to update it later today with small cleanups suggested in code review, and then it will be ready to be merged.

**Comment by andywingo** [comment]
AFAIU the cleanups are not functional in nature -- i.e. the code is correct as is.  For that reason, closing the bug.  If you have a cleanup you want landed on lwaftr_nutmeg please open a PR (maybe you have and we haven't gotten to it yet), but let's focus on lwaftr_olive in general for things not related to milestone v1.1.
