### ISSUE TITLE
ICMP echo app erroneously inits responses with TTL of incoming packet

### ISSUE THREAD

**Issue by wingo** [Igalia/snabbswitch#1069]
The ICMP echo app erroneously inits responses with TTL of incoming packet.  The standard thing to do is to init the response with the default TTL.  We should fix this in both the IPv6 and IPv4 apps.

**Comment by dpino** [comment]
Right, I think the default TTL of ICMP packets is 64. Confirmed, ICMP packets in Linux have a TTL value of 64 and RFC1700 (Assigned numbers) states:

_The current recommended default time to live (TTL) for the Internet Protocol (IP) [45,105] is 64._
