### ISSUE TITLE
Snabb top interface view does not report RX/TX of non-master queue

### ISSUE THREAD

**Issue by dpino** [Igalia/snabbswitch#1134]
When running the lwAFTR on a RSS configuration, if opening `snabb top`, the _interface view_ do not report any traffic in or out to one of the queues. However, if entering the _tree view_ mode there's traffic on that instance.

Here are two screenshots with the same instance on _interface view_ and _tree view_ modes.

Interface view:

![snabb-rss-interface-view](https://user-images.githubusercontent.com/11567/42213686-c8c10f3a-7eb9-11e8-864e-15d22c3c768f.png)

Tree view:

![snabb-rss-tree-view](https://user-images.githubusercontent.com/11567/42213696-d10403f0-7eb9-11e8-9940-d6242ee81a59.png)

**Comment by takikawa** [comment]
#1148 addresses this (it will be non-zero), but it will show global stats for the NIC if that's ok. Making it show only the enabled queue counters for that process & NIC takes more work.

**Comment by dpino** [comment]
It sounds good to me, the main issue was showing reporting zero on an instance which clearly means there's something wrong. If an user wants to know the traffic per week, can always focus that instance in tree view.
