### ISSUE TITLE
Missing argument in Manager:update_configuration

### ISSUE THREAD

**Issue by benagricola** [Igalia/snabbswitch#1157]
Just a quick one which I ran into implementing my own ptree `support` module - It looks like the call to `support.update_mutable_objects_embedded_in_app_initargs` (https://github.com/Igalia/snabb/blob/lwaftr/src/lib/ptree/ptree.lua#L535) is missing the schema name argument, causing various weirdness.

As far as I can tell this should always have the schema name passed, and it seems to work correctly once added. Happy to submit a PR with the fix but want to confirm I'm not missing something here :)

**Comment by dpino** [comment]
Thanks for reporting the issue. It seems to me too that the call is missing the `schema_name` argument. If you send a PR, and CI tests do not complain, I will merge it.
