### ISSUE TITLE
Make the tests run faster

### ISSUE THREAD

**Issue by kbara** [Igalia/snabbswitch#167]
Right now, it takes about one second per end-to-end test. Having them be ~instant would be nicer.
Any interest in fixing this, @dpino or @aperezdc ? :-)

**Comment by dpino** [comment]
OK, I think it makes sense. `check` is mainly used for running the tests.

**Comment by dpino** [comment]
I have a patch for this. I will send it later.

**Comment by kbara** [comment]
Thanks, looking forward to it. :-)
