### ISSUE TITLE
Factor fragmentation support into separate app(s)

### ISSUE THREAD

**Issue by andywingo** [Igalia/snabbswitch#180]
It would seem that it is possible to factor out the fragmentation code in the lwaftr to separate apps.  If we could do this, it would be so nice for the code, and it would enable re-use by other applications.  Thanks to Marcel Wiget for the idea.

**Comment by kbara** [comment]
It should be doable, and make a number of things much nicer. I wanted to do that before the alpha release, but didn't have time.

**Comment by dpino** [comment]
In case of moving out the code, what would make more sense, to move it to its own app or to a protocol library? It seems to me it should be a protocol library, same as `ipv4.lua` or `ethernet.lua`.

**Comment by andywingo** [comment]
I took a look and the overhead of factoring out reassembly to its own apps -- because I guess we would need separate apps for reassembly and for fragmentation -- the overhead for that would take us from being able to do 3.84+3.84 MPPS of 550-byte packets under the benchmark scenario down to 3.68+3.68 MPPS or so.  It's conceivable that if we were able to assume that the incoming packet is not fragmented, that simplification in the lwaftr would gain us back that loss.  I'll see if it's doable easily.

**Comment by andywingo** [comment]
Fixed in #195 / #197.  The perf penalty I note above is doubled because of adding the fragmentation apps.  If we are struggling for performance, we can pull this code back in, but in a way that doesn't add the implementation to lwaftr.lua.
