### ISSUE TITLE
Look up binding table entries for IPv6 packets using the IPv4 address in their payload

### ISSUE THREAD

**Issue by andywingo** [Igalia/snabbswitch#182]
This allows us to use a single table.

**Comment by dpino** [comment]
There is something I don't understand about this issue and it's that in `from_b4` function this is already happening as far as I understand.

```lua
if in_binding_table(lwstate, ipv6_src_ip, ipv6_dst_ip, ipv4_src_ip, ipv4_src_port) then
...
end
```

https://github.com/Igalia/snabbswitch/blob/lwaftr_olive/src/apps/lwaftr/lwaftr.lua#L746

Where `ipv4_src_ip` and `ipv4_src_port` are fetched from the IPv6 packet payload without decapsulating the packet.

**Comment by andywingo** [comment]
Ah, interesting.  I hadn't noticed that.  In that case let's merge your PSID work and refactor incrementally; seems we're not as far off as I thought we were.
