### ISSUE TITLE
Release v2.4

### ISSUE THREAD

**Issue by wingo** [Igalia/snabbswitch#305]
We are going to make a v2.4 maintenance release on top of `lwaftr_starfruit`.  We'll be listing things here that need to be back-ported from the main `lwaftr` branch back to `lwaftr_starfruit`.

**Comment by wingo** [comment]
- [x] https://github.com/snabbco/snabb/pull/707 (possibly already present in `lwaftr_starfruit` via a different path; not sure)

**Comment by wingo** [comment]
- [x] https://github.com/snabbco/snabb/pull/783

**Comment by wingo** [comment]
All of those previous ones are from before the lwaftr was merged.  After, it gets more complicated -- we have to rebase instead of merging.  I don't know if it is worth it.  I will attempt to assemble a list here:
- [x] https://github.com/Igalia/snabb/pull/291
- [x] https://github.com/Igalia/snabb/pull/294

**Comment by wingo** [comment]
- [x] https://github.com/snabbco/snabb/pull/827
- [x] https://github.com/snabbco/snabb/pull/866

**Comment by wingo** [comment]
OK that's all I can see.

**Comment by kbara** [comment]
https://github.com/snabbco/snabb/pull/707 is already in lwaftr_starfruit as commit 5528edbae217d22a6cab52d638e4e88574e98530

**Comment by kbara** [comment]
https://github.com/snabbco/snabb/pull/783 is already in lwaftr_starfruit as commit 940dc86027e2f71ed291aa9afe717bd278971570

**Comment by wingo** [comment]
- [x] https://github.com/snabbco/snabb/pull/909

**Comment by kbara** [comment]
291 is absolutely essential, and 294 is moderately important. Definitely both worth it.

**Comment by kbara** [comment]
snabbco#827 and  snabbco#866 backported via https://github.com/Igalia/snabb/pull/307

**Comment by wingo** [comment]
#291 via https://github.com/Igalia/snabb/pull/306#issuecomment-216524166

**Comment by dpino** [comment]
#294 via #308

**Comment by dpino** [comment]
#311 via #304:
- #304 is a backport of #909 to `lwaftr` branch.
- #311 is a backport of #304 to `lwaftr_starfruit` branch. 

#311 includes all commits from #304 except the "with_restart" commit.

**Comment by wingo** [comment]
Whew, done; tagged as v2.4.  Thank you both, @dpino and @kbara!
