### ISSUE TITLE
`snabb lwaftr loadtest` should be able to find the maximum load at which there is X% of loss over T time

### ISSUE THREAD

**Issue by wingo** [Igalia/snabbswitch#352]
`snabb lwaftr loadtest` should be able to find the maximum load at which there is X% of loss over T time.

An algorithm to find this out would be to ramp up from zero to some point where it starts dropping, and then stay there and only ramp up farther if dropping stops.  We could limit this process to some duration.

**Comment by dpino** [comment]
Fixed by https://github.com/Igalia/snabb/pull/1021 and https://github.com/Igalia/snabb/pull/1045
