### ISSUE TITLE
Intermittant bus error; Snabb refuses to run again until /var/run/snabb is cleared

### ISSUE THREAD

**Issue by kbara** [Igalia/snabbswitch#357]
Every once in a while, Snabb has a bus error. After this error occurs once, it occurs every time Snabb is run with certain commands (such as `snabb lwaftr check`, but not `snabb gc` or `snabbmark`)

The error, triggered from the lwaftr's end-to-end.sh tests, ends up looking something like this: 

`5623 Bus error               (core dumped) ${SNABB_LWAFTR} check $1 $2 $3 ${TEST_OUT}/endoutv4.pcap ${TEST_OUT}/endoutv6.pcap $6`

I saw it once, several months ago. Intensive testing of a (probably) unrelated problem has let me reproduce it a dozen times since yesterday - about once every 30 runs of the end-to-end.sh test suite on one machine, and once every 90 runs on a second machine.  Neither machine has NICs that Snabb can use.

**Comment by lukego** [comment]
Bus error can be easier to diagnose when you know which instruction triggers it. I usually run the process in GDB and get a backtrace. (If the instruction is in JIT code then I suppose you need `-jdump` to match the instruction address.)

I have also noticed on lab servers that `Segmentation fault` errors generate a syslog entry that includes the instruction pointer, faulting address, and insightful flags. Could be true for bus error too?

**Comment by wingo** [comment]
i think this should be fixed now that we have supervisor processes; in any case I haven't seen it in the last months.
