### ISSUE TITLE
Forward-port features from the v2.9 release to lwaftr

### ISSUE THREAD

**Issue by wingo** [Igalia/snabbswitch#359]

**Comment by wingo** [comment]
Are we missing 432a4c1ae497049efd3f84bc8138b5ff3964def2 ?  It's part of 2.4 but I don't see it on lwaftr already.

**Comment by dpino** [comment]
We have refactored how NDP and ARP retries work. Now in lwaftr branch NDP retries don't use timers. This commit is not necessary.

https://github.com/Igalia/snabb/commit/9e86b23880b2dab4013cbf66d174469588bc12d8

**Comment by wingo** [comment]
OK then it looks like this bug is covered by #371 #372 #373 #374 then, thanks :)

**Comment by wingo** [comment]
done, thank you @dpino
