### ISSUE TITLE
Do not use timers to implement NS requests and retries

### ISSUE THREAD

**Issue by dpino** [Igalia/snabbswitch#365]
Luke suggested in https://github.com/snabbco/snabb/pull/945/#issuecomment-227079544 to not rely on timers to implement data-plane logic.

Redo Neighbour Solicitation requests, as well as NS retries, following Luke's guidelines.

**Comment by kbara** [comment]
We should make ARP use this approach too (right now, it has no retries).

**Comment by dpino** [comment]
Implemented in #368.
