### ISSUE TITLE
Detecting memory errors with lwaftr check

### ISSUE THREAD

**Issue by dpino** [Igalia/snabbswitch#441]
I've been thinking on how to detect memory errors.

Bugs #439 in #437 were due to memory errors. Our test suite included tests for these cases but since the end-to-end test only sends one packet these memory errors were not triggered. To trigger these errors it would have been necessary to send the same packet several times.

Instead of creating specific datasets with the same packet repeated several times, I think it would work better if we make "lwaftr check" to do this job for us.  I would keep "lwaftr check" as it is and additionally run another test that sends a packet several times in a loop and direct its output to a sink.

Why not modifying lwaftr check and make it run in a loop always? There are some difficulties. Snabb runs for a certain period of time and the number of packets sent may vary in different runs. Having a different number packets sent spoils the test (output wouldn't match and neither the counters). Using `done` instead of `duration` has the same problem (done is not called in deterministic time). Even if we could hack a work around the output files would increase considerably, increasing the total size of the project. For this reason, I prefer to keep lwaftr check as it is and additionally run a "memory test".

**Comment by kbara** [comment]
Yep.... that's one of the reasons why I've repeatedly said we should run overnight tests (and on mixes of packets, not just one repeated 50 times or something), and keep talking about needing more test coverage.

**Comment by dpino** [comment]
Implemented in #443
