### ISSUE TITLE
Remove old benchmarking tools

### ISSUE THREAD

**Issue by dpino** [Igalia/snabbswitch#445]
`lwaftr/tests/end-to-end/` folder contains old benchmarking utilities which are no longer used AFAIK:
- benchmark-end-to-end.sh: Was a copy-paste of `end-to-end.sh` tests which run with the `apps/lwaftr/benchmark.lua` script instead.
-  benchmark-pcaps.sh: Similar to `benchmark-end-to-end.sh` but runs in one test case.
-  benchrun.lua: Runs a command N times and prints out some stats (average, standard deviation, etc).

The `apps/lwaftr/benchmark.lua` script loops through a given pcap input and pushes packets to its correspondent nic interfaces (inet or b4). 

Since we are no longer using these tools and they are not run automatically either, I think they should be removed unless they still can be of some use and we can refactor them and update them to something useful. Thoughts? @kbara @wingo

**Comment by wingo** [comment]
On Mon 19 Sep 2016 20:00, Diego Pino notifications@github.com writes:

> Since we are no longer using these tools and they are not run
> automatically either, I think they should be removed unless they still
> can be of some use and we can refactor them and update them to something
> useful. Thoughts? @kbara @wingo 

SGTM.

Andy

**Comment by kbara** [comment]
Probably for the best. Is the idea to then have to run the full hydra performance testing suite to get these numbers?

**Comment by dpino** [comment]
If we want Hydra to run these benchmarks we would need to rework them, because I think at this moment these tests cannot be run (they code is broken).

We only paid attention to these tests while developing the prototype, and actually we shortly stop use them as a means to improve performance, that's when "lwaftr bench" landed. I'm all in for removing these code, specially since we're planning to update lwaftr in upstream soon.
