### ISSUE TITLE
Handle stdout in a non-conflicting way overall

### ISSUE THREAD

**Issue by teknico** [Igalia/snabbswitch#463]
Need: using CSV stats generated by the `bench` lwAftr command.
Status: the `bench`, `run` and `transient` lwAftr commands emit CSV stats to `stdout`.
Conflict: the binding table code emits log messages to `stdout`, interfering with the CSV stats.

Proposal 1: make the mentioned commands emit CSV stats to a file, whose path is passed on the command line.
Proposal 2: make the binding table code emit log messages to `stderr`.
Proposal 3: do both things.

Aside: the binding table code emits log messages under control of the `SNABB_LWAFTR_VERBOSE`, defaulting to `true`. It is the only code doing so: other code uses a `verbose` command line flag, if anything.

**Comment by wingo** [comment]
Let's start with (2) :)

**Comment by teknico** [comment]
Unfortunately the whole codebase is strewn with calls to `print` (`stdout` only), and even `io.stdout:write`, not conditioned by debug flags, so using `stdout` for uncorrupted data output is a lost cause right now. :-(

Proposal 2 would entail a deep change of paradigm for both our code and the whole app, a huge, sprawling patch, and a prolonged fight with upstream: it seems more effective to go with proposal 1.

**Comment by teknico** [comment]
Fixed by #468 and #472.
