### ISSUE TITLE
nh_fwd cache refresh packets need entropy

### ISSUE THREAD

**Issue by mwiget** [Igalia/snabbswitch#476]
When testing a single flow over several snabb instances  via ECMP, the vMX will use hash method to decide over which egress interface to send the cache refresh packet it has received from any of the Snabb instances. If this is just a single flow from the same IP source/destination pair, it will always pick the same one, which can be different from the one it has received it. 
While not strictly a problem in a real life deployment, adding some variance to the hash packet in form of a random source UDP/TCP port will greatly increase the likelyhood for nh_fwd to learn the next hop mac address quickly.

**Comment by dpino** [comment]
I have been working in this bug for a while. I have some doubts I'd like to clarify.

My understanding is that either the IPv4 destination port of an IPv4 packet as well as a IPv4-in-IPv6 packet gets overwritten by a random value. Overwriting the port on a TCP packet implies to recalculate the TCP checksum, which involves building a pseudo-header. UDP packets can have their checksum set to zero, so they can be skipped. In case the packet is an ICMP packet, the destination port is the ICMP packet id field. So it would be necessary to inspect a packet payload to see if it's TCP, UDP or ICMP.

On the other hand, I started exploring the lib/protocol libraries to build the refreshment packet. The libraries include methods for recomputing the checksum. I think that's more convenient than hand crafting the pseudo-header and compute the checksum manually. What do you think about it?

**Comment by dpino** [comment]
Fixed in #704 (snabbvmx branch) and #766 (lwaftr branch).

**Comment by mwiget** [comment]
This change breaks for ICMP packets:
https://github.com/Igalia/snabb/blob/lwaftr-snabbvmx/src/apps/lwaftr/nh_fwd.lua#L154-L161

tcp_hdr is undefined at line 161 for ICMP packets.
