### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by wingo** [Igalia/snabbswitch#499]
We have lots of stale branches in this repo.  I propose to remove all of them except `lwaftr` and any branch for an open PR.  We will also keep `lwaftr_starfruit` until we are no longer supporting users on that branch.  Historical releases are just as well taken from tags than branches, and tags don't clutter the "make a PR" UI.

**Comment by teknico** [comment]
Yes, please.

**Comment by kbara** [comment]
+100000000000

**Comment by wingo** [comment]
I took a look at the branches and here is how I see things.  Check the "to-delete" set to see if anything you care about is there.

## Keep, main dev branch
- https://github.com/Igalia/snabb/tree/lwaftr

## Keep, legacy release branch

Remove when we migrate users to a new release branch
- https://github.com/Igalia/snabb/tree/lwaftr_starfruit

## Keep, active PR on Igalia/snabb
- https://github.com/Igalia/snabb/tree/merge-next-to-lwaftr

## Keep, active PR on SnabbCo/snabb

There are all from me.  Surely I should be creating these in
wingo/snabb though, so as to confine the mess.
- https://github.com/Igalia/snabb/tree/traffic-loop
- https://github.com/Igalia/snabb/tree/numa-upstream
- https://github.com/Igalia/snabb/tree/virtio-packet-shift
- https://github.com/Igalia/snabb/tree/streaming-ctable
- https://github.com/Igalia/snabb/tree/multi-copy
- https://github.com/Igalia/snabb/tree/binary-search

## Delete, dead
- https://github.com/Igalia/snabb/tree/2-8-backports
- https://github.com/Igalia/snabb/tree/add-lwaftr
- https://github.com/Igalia/snabb/tree/apps
- https://github.com/Igalia/snabb/tree/arppass
- https://github.com/Igalia/snabb/tree/basicnat-dispatch
- https://github.com/Igalia/snabb/tree/change-log-v2.1
- https://github.com/Igalia/snabb/tree/changelog-v2.7
- https://github.com/Igalia/snabb/tree/ctable
- https://github.com/Igalia/snabb/tree/dynasm-all-the-vregs
- https://github.com/Igalia/snabb/tree/fix-num-desc-info
- https://github.com/Igalia/snabb/tree/fix-test-ipv6-packet-not-found-lwaftr
- https://github.com/Igalia/snabb/tree/fix-vlan-tag-untag
- https://github.com/Igalia/snabb/tree/forward-port-to-lwaftr
- https://github.com/Igalia/snabb/tree/fraggle-rock
- https://github.com/Igalia/snabb/tree/issue409-testing
- https://github.com/Igalia/snabb/tree/l2fwd
- https://github.com/Igalia/snabb/tree/latency-histogram
- https://github.com/Igalia/snabb/tree/lookup_psid
- https://github.com/Igalia/snabb/tree/lwaftr-integration
- https://github.com/Igalia/snabb/tree/lwaftr-lib-numa
- https://github.com/Igalia/snabb/tree/lwaftr-to-2016.09
- https://github.com/Igalia/snabb/tree/lwaftr_incoming_icmp
- https://github.com/Igalia/snabb/tree/lwaftr_nutmeg
- https://github.com/Igalia/snabb/tree/lwaftr_olive
- https://github.com/Igalia/snabb/tree/lwaftr_rambutan
- https://github.com/Igalia/snabb/tree/lwaftr_run-virtio_net
- https://github.com/Igalia/snabb/tree/lwaftr_starfruit_rainbow_ponies
- https://github.com/Igalia/snabb/tree/lwaftr_starfruit_run_nohw
- https://github.com/Igalia/snabb/tree/lwaftr_with_virtio_net
- https://github.com/Igalia/snabb/tree/lwaftrctl-5
- https://github.com/Igalia/snabb/tree/lwnutmeg_backport_vlanrefactor
- https://github.com/Igalia/snabb/tree/lwolive-header-refactor
- https://github.com/Igalia/snabb/tree/lwolive-l2size
- https://github.com/Igalia/snabb/tree/lwolive-l3mtu
- https://github.com/Igalia/snabb/tree/lwsf_numa
- https://github.com/Igalia/snabb/tree/lwsf_perf_tools
- https://github.com/Igalia/snabb/tree/move-nexthop
- https://github.com/Igalia/snabb/tree/ndp-without-timers
- https://github.com/Igalia/snabb/tree/nfv/icehouse
- https://github.com/Igalia/snabb/tree/no-backpressure
- https://github.com/Igalia/snabb/tree/on-a-stick-vlan
- https://github.com/Igalia/snabb/tree/packet-shift
- https://github.com/Igalia/snabb/tree/pci_bind_upstream
- https://github.com/Igalia/snabb/tree/perf-docs
- https://github.com/Igalia/snabb/tree/rate-limit-backport
- https://github.com/Igalia/snabb/tree/refactor_read_conf
- https://github.com/Igalia/snabb/tree/release-notes-2.4
- https://github.com/Igalia/snabb/tree/release-notes-2.5
- https://github.com/Igalia/snabb/tree/removestaletodo
- https://github.com/Igalia/snabb/tree/revert-2d25d8
- https://github.com/Igalia/snabb/tree/revertcounteredge
- https://github.com/Igalia/snabb/tree/ronsils
- https://github.com/Igalia/snabb/tree/rxstatistics
- https://github.com/Igalia/snabb/tree/snabbvmx-mi2
- https://github.com/Igalia/snabb/tree/tail-calls-do-not-contribute-to-unroll-counter
- https://github.com/Igalia/snabb/tree/update-documentation
- https://github.com/Igalia/snabb/tree/virtio-noodlings
- https://github.com/Igalia/snabb/tree/vitamin-c
- https://github.com/Igalia/snabb/tree/wip-multi-copy

**Comment by kbara** [comment]
LGTM

**Comment by wingo** [comment]
Done, tx for review to you both.  Probably now you want to `git fetch --prune Igalia` or something.

FWIW the deleted heads are:

Branch 2-8-backports:
- 562fb0f8954ea7e8ba63037bf54b7d93df2edf30 Change --cpu mentions to taskset/numactl

Branch add-lwaftr:
- 5c337d0750bb87db7a99c81491816f43976cc82c Add lwaftr branch.

Branch apps:
- 004036e9e29876464b539c87a68fae895f04db28 Merge branch 'igalia' into apps

Branch arppass:
- dd69563c76159fb02fded679c36bc36a20083996 Fixed byte order conversion

Branch basicnat-dispatch:
- b34a44710d26108d4452e75bdfc087eb13fd8c7b fix thing i forgot to update

Branch change-log-v2.1:
- 89da7fbfb71332f682c09dae6d91244cf62cd010 Update change log.

Branch changelog-v2.7:
- eee1ca7eb11b1932e76a7cc993f87e5e15fcdba4 v2.7 changelog

Branch ctable:
- 5b9400a739f3f800a2bbe52c5dcd461c9ee15fe7 Move ctable documentation to src/lib/README.md, fix nits

Branch dynasm-all-the-vregs:
- 4257e0a022988d5c1892a853e2102d1ac4e53cf2 Update Lua DynASM for upstream DynASM changes

Branch fix-num-desc-info:
- 653d0ddf4a7c31ec9ae805e797390ffa3cb4e327 Update performance-tuning.md

Branch fix-test-ipv6-packet-not-found-lwaftr:
- b727704a956e7cde69a2fefba0ade5d77aeaecd7 Add test 'Testing sending non-IPv4 traffic to the IPv4 interface'

Branch fix-vlan-tag-untag:
- 65cdc1c7f22ebf4390ef95e88e84ac35662c8aa0 Cast VLAN tags as int32

Branch forward-port-to-lwaftr:
- 3b1dfb4cdb9db7847bd6d892f881a1c743652b6f Forward-port CHANGELOG.

Branch fraggle-rock:
- e826125a4457430f1211eaf497c3d5c48fca05ea Split VLAN support out into separate apps

Branch issue409-testing:
- 784d291b2cde0e1068a2f34b69dafa05941a1d4f Trying to reproduce issue 409

Branch l2fwd:
- 347cf4439bb4b2ce0f2df9500fb0a9adf3db2b0b Implement l2fwd-like app

Branch latency-histogram:
- 08fe89768007bf4c27a0829f6a80aa37880d38a5 app.main() measures latency by default

Branch lookup_psid:
- 90fe0ead6b2707e990b47721fd9dbf823e661f10 Move dump related code to its own file

Branch lwaftr-integration:
- 8364729b1cc4975e1c03e389de162e7e1bd7f3ed Import lightweight 4-over-6 AFTR

Branch lwaftr-lib-numa:
- 976b5dfe3cb858e1b20a69cc0a752e2082957753 lwaftr loadtest uses lib.numa

Branch lwaftr-to-2016.09:
- 9e7b1eb1db90fd50a501e0c482cdf24277ee7d1a Merge branch 'master' into lwaftr-merge-master

Branch lwaftr_incoming_icmp:
- ed5045d0376c8fbbb65853821028f24ccf0a5b95 All the incoming-ICMPv6 tests now pass

Branch lwaftr_nutmeg:
- 8c9bf107461afd7512cd4c13d92539f8884a2d85 Merge pull request #171 from Igalia/lwnutmeg_changelog1.2

Branch lwaftr_olive:
- 2e09ee5dcef2d03851915f3d99da259c5621843b Merge pull request #194 from Igalia/tonsils

Branch lwaftr_rambutan:
- 2126a891d4c0cd889dabf89501c71fc6f9e02792 Merge pull request #216 from aperezdc/lwaftr_rambutan_remove_unused_var

Branch lwaftr_run-virtio_net:
- ec90aad161d260866a23e26bfeae6b331cca83d3 Add support for running `snabb-lwaftr run` with virtio_net drivers

Branch lwaftr_starfruit_rainbow_ponies:
- 65db73844537f725dfa4f64e9ab8f754e1edf4b9 Fix log format expression

Branch lwaftr_starfruit_run_nohw:
- 9f4b1b50473f018d5525dea86a99d959b276ad3c Fix --bt long option (ups)

Branch lwaftr_with_virtio_net:
- 40faf41f148bfc0ad90ef1a66bacf17dafb5681f Use VirtioNet driver in lwaftr-run

Branch lwaftrctl-5:
- ee06468353bf6553eea8a454f2a99356ec417195 Add configuration files for 5 VM

Branch lwnutmeg_backport_vlanrefactor:
- 8b351cfe2c34b1077472b6fa5b58cff5b26b19df Removed the IPv4 fragmentation tests from backport

Branch lwolive-header-refactor:
- 421724e94f7d99685f1d0004d3e9736fa8d25857 Refactor header handling, make outgoing ICMP work

Branch lwolive-l2size:
- 8ca0573a153156fccc74fa8d85874ae39c59c29d Refactoring: vlans without overwriting constants

Branch lwolive-l3mtu:
- 28e072dcb07412942cfedce7b42dfc994a4a9f38 MTU settings are now L3 rather than L2 based.

Branch lwsf_numa:
- 401b5245c3e8665003c073d403648cff5550321d Work around a broken `getcpu'

Branch lwsf_perf_tools:
- 3a89d41e08e1e6c0a56481d9e1961a299176edf6 Add --ring-buffer-size option to --run

Branch move-nexthop:
- aba846ce0ca0062c82783e8eb6388c51b847293d fix nexthop test

Branch ndp-without-timers:
- f6d6bef008e468faf6536f28df304ddb8f804b23 Handle NS requests and retries without timers

Branch nfv/icehouse:
- b8bdbec54dfc6cceb2c241322b9eb4c1c355f418 Merge pull request #249 from virtualopensystems/small_fix

Branch no-backpressure:
- c317ddc31e442e5763dcd8908e609387a24a7776 Remove all backpressure

Branch on-a-stick-vlan:
- 41f300ff7268bd437227e9a14164ddef8a1f5fc6 Pass load_on_a_stick arguments as hash

Branch packet-shift:
- 12f77a31b8f5b5edc6d5056fdf13f93eb38a47d1 Fix allocate/new_packet mixup.

Branch pci_bind_upstream:
- dcaf4f933360071caeebfaf0ffd3bff3ad7478ca pci_bind: A utility to bind/unbind PCI cards

Branch perf-docs:
- 0f2fa1992c5eedd40563f02d67bf6cc490cd9c25 More performance documentation updates

Branch rate-limit-backport:
- 099fb27e8eae1bed3f49b022c9a377070582a458 loadtest prints out bitrates with overhead

Branch refactor_read_conf:
- 42fbb32e5b357292c9b5fc41633f6945c529bc94 Refactor 'read_conf'

Branch release-notes-2.4:
- 9c93c5eb680a169039579cb8062d8616b9c9ebfa Document new command line options

Branch release-notes-2.5:
- f37029cbc3b0aa4faf0ea7b737e2fac2ca323c31 Add release notes

Branch removestaletodo:
- d086c9e29531d4a368df10efc002262865989d59 Removed stale TODOs

Branch revert-2d25d8:
- dfbf2c5da077bf5c66ba5064b5f18e5ed433e387 Revert "Move the line-oriented counters towards the edges of the app network"

Branch revertcounteredge:
- d7f51cdf7cebaf81571458b249d56f28502a4c4a Revert moving line oriented counters to app network edge

Branch ronsils:
- 6b4d7890d2d4e43a26ce5136be1dd762a330041d Use CSV stats in benchmark instead of statistics apps

Branch rxstatistics:
- 282c11aa336aa58073687c1f511f83ab7ff18df0 Enable rxstatistics

Branch snabbvmx-mi2:
- b3d2ef4cdfb493b62218d603089aae224c1c7f5f Remove unused app 'Repeater'

Branch tail-calls-do-not-contribute-to-unroll-counter:
- 9a1294c977de8c5f35451ed290a67585e47fbcab Don't count tail calls towards loop unroll limit.

Branch update-documentation:
- 285f108359fb6dcc67d6f8fa7801c34650b77a6c Merge branch 'lwaftr' into update-documentation

Branch virtio-noodlings:
- bac60c980f4c80e322bf3ded1e45898cf6ffac8d virtio-net driver: Use direct descriptors

Branch vitamin-c:
- 1bda00ef69871482ddd18341d2951272158a576d Use LuaJIT htons/htonl

Branch wip-multi-copy:
- 143df6d12fc140b176dd3fca2034fef262a089c1 Harmonize streaming and non-streaming test cases
