### ISSUE TITLE
lwaftr :  configuration with vlan ignores mtu  setting

### ISSUE THREAD

**Issue by blourdel** [Igalia/snabbswitch#504]
In a lwaftr  setup with vlan configured for ipv4 and ipv6 traffic, 1519B packets are dropped while smaller packets are processed (1518B works) regardless of the mtu setting. The behavior is the same with same or different vlan-id for ipv4 and ipv6.

I am running snabb lwaftr version v1.1.11

**How to reproduce**

While configuring vlan for both ipv6 and ipv4, send 1519Byte ipv4 or ipv4/ipv6 encapsulated packet to the lwaftr. They are all dropped. If packet size is reduced, all packets are going through the lwaftr. The configuration has both ipv4 and ipv6 mtu set to 9500B.

**Topology**
IXIA packet generator -----router------snabb

**Configuration**

hairpinning = false,
binding_table = binding_table.txt.s,
aftr_ipv6_ip = 2001:db8::1,
aftr_ipv4_ip = 1.1.0.20,
aftr_mac_inet_side = 02:3d:dc:07:0b:00,
inet_mac = 44:f4:77:bc:c5:cf,
aftr_mac_b4_side = 02:3d:dc:07:0b:00,
next_hop6_mac = 44:f4:77:bc:c5:cf,
ipv4_mtu = 9500,
ipv6_mtu = 9500,
vlan_tagging = true,
v4_vlan_tag = 100,
v6_vlan_tag = 100,
policy_icmpv4_incoming = allow,
policy_icmpv4_outgoing = drop,
policy_icmpv6_incoming = allow,
policy_icmpv6_outgoing = drop,

**Packet capture**

**Binding table**
[zipped_binding_table.txt.s.gz](https://github.com/Igalia/snabb/files/541751/zipped_binding_table.txt.s.gz)

**Comment by mwiget** [comment]
Which version of the container are you running? There is no tag v1.1, but v1.1.0, which is pretty old.
Ideally you run https://github.com/mwiget/vmxlwaftr/blob/igalia/tests/collect-support-infos.sh against the running container, which collects all required files for reproduction (and version checking).

**Comment by blourdel** [comment]
Hello,

I am running container version v1.1.11.
I am attaching the support info here:
[support-info-20161020-0347.tar.gz](https://github.com/Igalia/snabb/files/541999/support-info-20161020-0347.tar.gz)

**Comment by dpino** [comment]
I run the test case in lwaftr-snabbvmx-v1.1 and development branch and I couldn't reproduce the bug in either cases. I run lwAFTR on-a-stick since there's no .cfg file pasted. I looked in the .tar and there are many .cfg and .conf files. I grepped "44:f4:77:bc:c5:cf" to get .conf file pasted in the bug report and figure out its correspondent .cfg file, but I couldn't find a .conf with that mac in the tar.

```
$ grep -Rn "44:f4:77:bc:c5:cf" *
```

Reproducing the test case with lwAFTR in on-a-stick mode is not quite the same. I think the problem might be that the SnabbVMX's configuration in use has a MTU value set to 1500 in both ipv4_interface and ipv6_interface parameters. In 1.1 version, SnabbVMX's MTU value overwrites the ones from lwAFTR's conf, but thanks to a recent change in the development branch now lwAFTR's MTU value is always honored.

If you paste SnabbVMX's config file I can try reproducing the issue on SnabVMX.

```
$ sudo ./snabb lwaftr run --cpu 7 --conf lwaftr-test.conf --on-a-stick 82:00.0
```

```
$ sudo numactl -m 0 taskset -c 3 ./snabb packetblaster lwaftr --src_mac 02:3d:dc:07:0b:00 --dst_mac 02:3d:dc:07:0b:00 --b4 2001:db9:200::1,10.10.0.0,1024 --aftr 2001:db8:2::1 --count 60000 --rate 3.1 --pci 0000:02:00.0 --vlan 100

vlan set to 100
v6+v4: 0.000+0.000 = 0.000000 MPPS, 0.000+0.000 = 0.000000 Gbps, lost nan%
v6+v4: 0.562+0.562 = 1.123568 MPPS, 1.785+1.605 = 3.389434 Gbps, lost 2.150%
v6+v4: 1.550+1.550 = 3.100157 MPPS, 4.924+4.428 = 9.352351 Gbps, lost 0.000%
v6+v4: 1.550+1.550 = 3.100001 MPPS, 4.924+4.428 = 9.351844 Gbps, lost 0.000%
v6+v4: 1.550+1.550 = 3.099994 MPPS, 4.924+4.428 = 9.351847 Gbps, lost 0.000%
v6+v4: 1.550+1.550 = 3.100026 MPPS, 4.924+4.428 = 9.351918 Gbps, lost 0.000%
v6+v4: 1.550+1.550 = 3.099976 MPPS, 4.924+4.428 = 9.351793 Gbps, lost 0.000%
v6+v4: 0.882+0.882 = 1.764074 MPPS, 2.802+2.520 = 5.321717 Gbps, lost 0.000%
```

**Comment by mwiget** [comment]
@blourdel Thanks for the tar file. I used the snabb binary from that file in my lab setup with a cross-over cable, adjusted the mac address and PCI address in test_snabb_snabbvmx_xe0.sh and ran it, leaving the .conf and .cfg file as is:

```
cat ./test_snabb_snabbvmx_xe0.sh
#!/bin/bash
echo "launching snabb snabbvmx on-a-stick on PCI 0000:03:00.0"
sudo usr/local/bin/snabb snabbvmx lwaftr --conf test-snabbvmx-lwaftr-xe0.cfg --id xe0 --pci 0000:03:00.0 --mac 02:3d:dc:07:0b:00
```

```
./test_snabb_snabbvmx_xe0.sh
launching snabb snabbvmx on-a-stick on PCI 0000:03:00.0
loading compiled binding table from ./binding_table.txt.s.o
compiled binding table ./binding_table.txt.s.o is up to date.
Hairpinning: no
nic_xe0 network ether 02:3d:dc:07:0b:00 mtu 9518
nic_xe0 vlan 100
IPv6 fragmentation and reassembly: no
IPv4 fragmentation and reassembly: no
lwAFTR service: enabled
Running without VM (no vHostUser sock_path set)
nh_fwd6: cache_refresh_interval set to 0 seconds
nh_fwd6: static next_hop_mac 02:02:02:02:02:02
loading compiled binding table from ./binding_table.txt.s.o
compiled binding table ./binding_table.txt.s.o is up to date.
nh_fwd4: cache_refresh_interval set to 0 seconds
nh_fwd4: static next_hop_mac 02:02:02:02:02:02
Ingress drop monitor: flush (threshold: 100000 packets; wait: 20 seconds; interval: 1.00 seconds)
1154.623981104: warning: Dropped more than 100000 packets; flushing JIT to try to recover. See https://github.com/Igalia/snabb/blob/lwaftr/src/program/lwaftr/doc/README.performance.md for performance tuning tips.
1174.623998549: warning: Dropped more than 100000 packets; flushing JIT to try to recover. See https://github.com/Igalia/snabb/blob/lwaftr/src/program/lwaftr/doc/README.performance.md for performance tuning tips.
```

Then I created the following packet generator and can pass packets > 1500 just fine. Using 2000:

```
$ cat run-gen.sh
#!/usr/bin/env bash

SNABB=../snabb/src/snabb

PCIDEV=0000:03:00.1
INTERFACE=enp4s0f0
RATE=1.1
CPU=6
if [ -z "$RATE" ]; then
  echo "Please specify rate in MPPS"
  exit 1
fi
FLOWS=200000
SMAC="02:02:02:02:02:02"
DMAC="02:3d:dc:07:0b:00"

echo $INTERFACE at $PCIDEV has $MAC, running at $RATE gbps

CMD="sudo taskset -c $CPU $SNABB packetblaster lwaftr $OPT  --src_mac $SMAC --dst_mac $DMAC --b4 2001:db9:200::1,10.10.0.0,1024 --aftr 2001:db8:2::1 --count $FLOWS --rate $RATE --pci $PCIDEV --vlan 100 --size 2000 # size --128  #--vlan 5"

echo $CMD

exec $CMD
```

This produces the following output:

```
$ ./run-gen.sh
enp4s0f0 at 0000:03:00.1 has , running at 1.1 gbps
sudo taskset -c 6 ../snabb/src/snabb packetblaster lwaftr --src_mac 02:02:02:02:02:02 --dst_mac 02:3d:dc:07:0b:00 --b4 2001:db9:200::1,10.10.0.0,1024 --aftr 2001:db8:2::1 --count 200000 --rate 1.1 --pci 0000:03:00.1 --vlan 100 --size 2000 # size --128 #--vlan 5
packetblaster lwaftr: Sending 200000 clients at 1.100 MPPS to 0000:03:00.1

IPv6: 2001:db9:200::1 > 2001:db8:2::1: 10.10.0.0:1024 > 8.8.8.8:12345
      source IPv6 and source IPv4/Port adjusted per client
IPv6 packet sizes: 2040

IPv4: 8.8.8.8:12345 > 10.10.0.0:1024
      destination IPv4 and Port adjusted per client
IPv4 packet sizes: 2000
vlan set to 100
v6+v4: 0.321+0.260 = 0.580807 MPPS, 5.285+4.195 = 9.479265 Gbps, lost 17.017%
v6+v4: 0.391+0.213 = 0.604438 MPPS, 6.439+3.444 = 9.883213 Gbps, lost 4.979%
v6+v4: 0.394+0.210 = 0.604386 MPPS, 6.495+3.389 = 9.883443 Gbps, lost 5.015%
v6+v4: 0.384+0.220 = 0.604570 MPPS, 6.329+3.555 = 9.883187 Gbps, lost 5.013%
v6+v4: 0.393+0.211 = 0.604413 MPPS, 6.471+3.412 = 9.883421 Gbps, lost 5.014%
v6+v4: 0.389+0.215 = 0.604479 MPPS, 6.406+3.477 = 9.883216 Gbps, lost 5.014%
```

Also tried MTU of 9000:

```
./run-gen.sh
enp4s0f0 at 0000:03:00.1 has , running at 1.1 gbps
sudo taskset -c 6 ../snabb/src/snabb packetblaster lwaftr --src_mac 02:02:02:02:02:02 --dst_mac 02:3d:dc:07:0b:00 --b4 2001:db9:200::1,10.10.0.0,1024 --aftr 2001:db8:2::1 --count 200000 --rate 1.1 --pci 0000:03:00.1 --vlan 100 --size 9000 # size --128 #--vlan 5
packetblaster lwaftr: Sending 200000 clients at 1.100 MPPS to 0000:03:00.1

IPv6: 2001:db9:200::1 > 2001:db8:2::1: 10.10.0.0:1024 > 8.8.8.8:12345
      source IPv6 and source IPv4/Port adjusted per client
IPv6 packet sizes: 9040

IPv4: 8.8.8.8:12345 > 10.10.0.0:1024
      destination IPv4 and Port adjusted per client
IPv4 packet sizes: 9000
vlan set to 100
v6+v4: 0.088+0.036 = 0.124669 MPPS, 6.407+2.615 = 9.022394 Gbps, lost 22.614%
v6+v4: 0.136+0.001 = 0.137632 MPPS, 9.880+0.093 = 9.972934 Gbps, lost 9.604%
v6+v4: 0.136+0.001 = 0.137632 MPPS, 9.875+0.098 = 9.972934 Gbps, lost 9.630%
v6+v4: 0.136+0.002 = 0.137635 MPPS, 9.841+0.132 = 9.972982 Gbps, lost 9.650%
```

Is the router between snabb and IXIA introducing the MTU limit by chance?

**Comment by blourdel** [comment]
I close this problem report. A switch in between snabb and the packet generator had a "by-default" mtu set, dropping packet over 1518. I confirm that vlan configuration are supporting large packet sizes.
