### ISSUE TITLE
Snabb config derive data format command

### ISSUE THREAD

**Issue by tsyesika** [Igalia/snabbswitch#529]
This issue is to provide a mechanism to see a YANG description of a data file based upon the corrisponding schema file. This would be achived by adding a command to the `snabb config` program which where a user could specify the module and the program would look up and parse the schema, derive the grammar and finally display descriptive YANG formatted data format.

The main use case for this would be so that one can verify their YANG schema by checking their corrisponding data format and would also help with reading/writing the data files for the SNABB layman.

Below is an example of a schema in a file and then the output of the command:

**Schema** - snabb_simple_router.yang
```yang
module snabb-simple-router {
  namespace snabb:simple-router;
  prefix simple-router;

  import ietf-inet-types {prefix inet;}

  leaf active { type boolean; default true; }

  container routes {
    presence true;
    list route {
      key addr;
      leaf addr { type inet:ipv4-address; mandatory true; }
      leaf port { type uint8 { range 0..11; }; mandatory true; }
    }
  }
}
```

**Command usage** - Bash shell
```sh
$ sudo ./snabb config derive-data-format -m apps/router/snabb_simple_router.yang
snabb-simple-router {
  routes {
    inet:ipv4-address {
      port uint8;
    }
  }
}
```

A question to me would be is this obvious enough? There is nothing to distinguish lists from containers other than knowing what the schema says and the entire point of this is to describe the data. I suppose some notation such as an asterisk following the key's type could be used.

Another suggestion could be add multiple enteries and leave a trailing "..." to suggest that it could continue.

Finally it'd be somewhat trivial and entirely possible to simply store mock values for all type primitives (and some extra commenly used ones such as those found in inet). These could then be subbed in to give you an examaple configuration file, this could simply have multiple list enteries everytime a list is specified showing the different configurations.

WDYT @wingo?

**Comment by wingo** [comment]
Hi!

For me I would indicate lists by appending "...".

See https://github.com/Igalia/snabb/blob/8c8dc727b0ded04be1899412c766bebd9530345d/src/lib/yang/README.md for some more discussion about this case.  In particular I don't think there's a need for an outer `snabb-simple-router {}` wrapper; wdyt?

**Comment by wingo** [comment]
Another possibility is to embed comments!  Maybe that can help.

**Comment by wingo** [comment]
Closing as merged.  Thank you @xray7224 !
