### ISSUE TITLE
end-to-end.sh - outputv6.pcap incorrect compared

### ISSUE THREAD

**Issue by chrgraf** [Igalia/snabbswitch#550]
Dear all,

I am trying to add an test to test_env.sh which shall have its pass-criteria based on the counters-file opposed to the resulting out.pcap.

Given tests_env.sh entry:
```
TEST_DATA=(
    "ICMP Test - pass-critria out.pcap"
    "icmp_snabbvmx-lwaftr-xe1.cfg" "icmp-ipv4-in.pcap" "empty.pcap" "" ""
    "icmp.lua"
```

**Expectation**
The test "ICMP Test - pass-critria out.pcap" as defined above shall ignore both resulting IPv4 and IPv6 pcaps and only check if the counters-file is matching.
If I have a misunderstanding here, then kindly correct me:)

**This error is displayed when running the end-to-end test:**
```
lab@ubuntu1:~/latest-snabb-binary/snabb/src/program/snabbvmx/tests/end-to-end$ sudo ./end-to-end.sh
Testing: ICMP Test - pass-critria out.pcap
loading compiled binding table from data/cg-binding_table.txt.s.o
compiled binding table data/cg-binding_table.txt.s.o is up to date.
nh_fwd4: cache_refresh_interval set to 0 seconds
nh_fwd4: static next_hop_mac 90:e2:ba:94:2a:bc
nh_fwd6: cache_refresh_interval set to 0 seconds
nh_fwd6: static next_hop_mac 90:e2:ba:94:2a:bc
done
cmp: EOF on data/empty.pcap
-rw-rw-r-- 1 lab lab 24 Nov  8 11:47 data/empty.pcap
-rw-r--r-- 1 root root 420 Nov  8 15:57 /tmp/endoutv6.pcap
Failure: ../../../../snabb snabbvmx check data/icmp_snabbvmx-lwaftr-xe1.cfg data/icmp-ipv4-in.pcap data/empty.pcap data/empty.pcap data/empty.pcap data/counters/icmp.lua
lab@ubuntu1:~/latest-snabb-binary/snabb/src/program/snabbvmx/tests/end-to-end$
```

**version**
```
lab@ubuntu1:~/latest-snabb-binary/snabb/src/program/snabbvmx/tests/end-to-end$ git log
commit 9c0739605e424222f91c7574a303d8b566578918
Author: Nicola Larosa <github@teknico.net>
Date:   Tue Nov 8 11:50:21 2016 +0100

    Let out-ipv6-* counters also count internally generated ICMPv6 packets, and update docs (#547)

commit eee906563afc9a8e33fb7627ae47d393e0cb6f58
Merge: ac4b0ec f907489
Author: Andy Wingo <wingo@pobox.com>
Date:   Tue Nov 8 10:26:56 2016 +0100

    Merge pull request #546 from Igalia/lwaftr-ctable

    Migrate lwaftr to use ctable instead of podhashmap
```

**config-files**

**cg-binding_table.txt.s**

```
$ cat data/cg-binding_table.txt.s
psid_map {
  10.10.0.0  {psid_length=6, shift=10}
  10.10.0.1  {psid_length=6, shift=10}
  10.10.0.10 {psid_length=6, shift=10}
}
br_addresses {
  2a02:587:f700::100,
}
softwires {
  { ipv4=10.10.0.0, psid=1, b4=2a02:587:f710::40 }
  { ipv4=10.10.0.0, psid=2, b4=2a02:587:f710::41 }
  { ipv4=10.10.0.0, psid=3, b4=2a02:587:f710::42 }
  { ipv4=10.10.0.0, psid=4, b4=2a02:587:f710::43 }
}
```

**icmp_snabbvmx-lwaftr-xe1.cfg**

```
$ cat data/icmp_snabbvmx-lwaftr-xe1.cfg
return {
  lwaftr = "icmp_snabbvmx-lwaftr-xe1.conf",
  settings = {
  },
  ipv6_interface = {
    ipv6_address = "",
    cache_refresh_interval = 0,
    fragmentation = false,
    mac_address = "02:cf:69:15:81:01",
    next_hop_mac = "90:e2:ba:94:2a:bc",
  },
  ipv4_interface = {
    ipv4_address = "192.168.5.2",
    cache_refresh_interval = 0,
    fragmentation = false,
    mac_address = "02:cf:69:15:81:01",
    next_hop_mac = "90:e2:ba:94:2a:bc",
  },
}
```

**icmp_snabbvmx-lwaftr-xe1.conf**

```
$ cat data/icmp_snabbvmx-lwaftr-xe1.conf
hairpinning = false,
vlan_tagging = false,
binding_table = cg-binding_table.txt.s,
aftr_ipv6_ip = fc00:168:10::2,
aftr_ipv4_ip = 192.168.10.2,
aftr_mac_inet_side = 02:cf:69:15:81:01,
inet_mac = 90:e2:ba:94:2a:bc
aftr_mac_b4_side = 02:cf:69:15:81:01,
next_hop6_mac = 90:e2:ba:94:2a:bc,
ipv4_mtu = 9000,
ipv6_mtu = 9000,
policy_icmpv4_incoming = allow,
policy_icmpv4_outgoing = drop,
policy_icmpv6_incoming = allow,
policy_icmpv6_outgoing = allow,
icmpv6_rate_limiter_n_packets = 300000,
icmpv6_rate_limiter_n_seconds = 4,
```

```
$ cat data/counters/icmp.lua
return {
   ["drop-all-ipv4-iface-bytes"] = 568,
   ["drop-all-ipv4-iface-packets"] = 4,
   ["drop-no-dest-softwire-ipv4-bytes"] = 568,
   ["drop-no-dest-softwire-ipv4-packets"] = 4,
   ["drop-out-by-policy-icmpv4-packets"] = 4,
   ["in-ipv4-bytes"] = 852,
   ["in-ipv4-packets"] = 6,
   ["out-ipv6-bytes"] = 364,
   ["out-ipv6-packets"] = 2,
}
```

```
$ cat test_env.sh
#/usr/bin/env bash

# Notice spaces and new lines are not taken into account.
TEST_DATA=(
    "ICMP Test - pass-critria out.pcap"
    "icmp_snabbvmx-lwaftr-xe1.cfg" "icmp-ipv4-in.pcap" "empty.pcap" "" ""
    "icmp.lua"

    "ICMP Test - pass-critria out.pcap"
    "icmp_snabbvmx-lwaftr-xe1.cfg" "icmp-ipv4-in.pcap" "empty.pcap" "" "icmp-ipv6-out.pcap"
    ""

    "IPv6 fragments and fragmentation is off"
    "snabbvmx-lwaftr-xe1.cfg" "" "regressiontest-signedntohl-frags.pcap" "" ""
    "drop-all-ipv6-fragments.lua"
)
TEST_SIZE=${#TEST_DATA[@]}
```

**pcaps**
[empty.pcap.gz](https://github.com/Igalia/snabb/files/578526/empty.pcap.gz)
[icmp-ipv4-in.pcap.gz](https://github.com/Igalia/snabb/files/578529/icmp-ipv4-in.pcap.gz)

Kindly have a look into the issue. I am have using wrong syntax or have a misunderstanding, please get me corrected.

thanks

christian

**Comment by dpino** [comment]
>The test "ICMP Test - pass-critria out.pcap" as defined above shall ignore both resulting IPv4 and IPv6 pcaps > and only check if the counters-file is matching. If I have a misunderstanding here, then kindly correct me:)

Right, that's correct. The test as it stated receives packets in the inet-side interface of the lwAFTR and expects no output in either inet and b4 interfaces. Reference to empty.pcap can be skipped though as "" implies empty.pcap:

```
"ICMP Test - pass-critria out.pcap"
"icmp_snabbvmx-lwaftr-xe1.cfg" "icmp-ipv4-in.pcap" "" "" ""
"icmp.lua"
```

However, the counters file reports that two packets go through the IPv6 interface and that's why the test fails.

So I took at what's in icmp-ipv4-in.pcap:

```
$ sudo tcpdump -t -qns 0 -r data/icmp-ipv4-in.pcap                                                                  
reading from file data/icmp-ipv4-in.pcap, link-type EN10MB (Ethernet)
IP 10.0.1.100.53 > 10.10.0.0.1024: UDP, length 0
IP 10.0.1.100.53 > 10.10.0.0.53: UDP, length 0
IP 10.0.1.100 > 10.10.0.0: ICMP echo reply, id 1024, seq 0, length 208
IP 10.0.1.100 > 10.10.0.0: ICMP echo reply, id 53, seq 0, length 208
IP 192.168.0.0 > 192.168.1.100: ICMP echo reply, id 1024, seq 0, length 208
IP 192.168.0.0.53 > 192.168.1.100.1024: UDP, length 0
```

And what's in `/tmp/endoutv6.pcap`:

```
$ sudo tcpdump -t -qns 0 -r data/icmp-ipv6-out.pcap
reading from file data/icmp-ipv6-out.pcap, link-type EN10MB (Ethernet)
IP6 2a02:587:f700::100 > 2a02:587:f710::40: IP 10.0.1.100.53 > 10.10.0.0.1024: UDP, length 0
IP6 2a02:587:f700::100 > 2a02:587:f710::40: IP 10.0.1.100 > 10.10.0.0: ICMP echo reply, id 1024, seq 0, length 208
```

There are two packets from icmp-ipv4-in.pcap that are being successfully encapsulated, when we expected none. Question is, should they be allowed according to the binding table? These are the packets that go through:

```
IP 10.0.1.100.53 > 10.10.0.0.1024: UDP, length 0
IP 10.0.1.100 > 10.10.0.0: ICMP echo reply, id 1024, seq 0, length 208
```

And the answer is yes, because of this softwire:

```
{ ipv4=10.10.0.0, psid=1, b4=2a02:587:f710::40 }
```

psid=0 is port range 0-1023, while psid=1 is range 1023-2047. The IPv4 packets have destination address 10.10.0.0:1024 and in the case of ICMP packets id works as port-range, which in this case is 1024, that means a valid port.

Perhaps your icmp-ipv4-in.pcap file contained more packets than you thought and that's why you didn't get the expected results. Perhaps you wanted a pcap file that contained only invalid ICMP packets, something like:

```
IP 10.0.1.100 > 10.10.0.0: ICMP echo reply, id 53, seq 0, length 208
IP 192.168.0.0 > 192.168.1.100: ICMP echo reply, id 1024, seq 0, length 208
IP 192.168.0.0.53 > 192.168.1.100.1024: UDP, length 0
```

With this input all packets would be discarded.

**Comment by chrgraf** [comment]
Hi Diego,

thanks for looking into it. 
First of all, your observation that the input-pcap has in total 6 packets and only two of them are valid is fully correct and 4 of them shall be discarded due to not matching the binding-table.

My original provided icmp.lua is reflecting this.

```
$ cat data/counters/icmp.lua
return {
   ["drop-all-ipv4-iface-bytes"] = 568,
   ["drop-all-ipv4-iface-packets"] = 4,
   ["drop-no-dest-softwire-ipv4-bytes"] = 568,
   ["drop-no-dest-softwire-ipv4-packets"] = 4,
   ["drop-out-by-policy-icmpv4-packets"] = 4,  <<< 4 packets get discarded due not matching binding-table
   ["in-ipv4-bytes"] = 852,
   ["in-ipv4-packets"] = 6,   <<<, 6 frames IPv4 input 
   ["out-ipv6-bytes"] = 364,
   ["out-ipv6-packets"] = 2,  <<< 2 packets get translated successfully
}
```

I am wondering if I still have a fully wrong understanding on how the test works.
I provided the lua counter-file correctly, knowing that "/tmp/endoutv6.pcap" is not empty (your observation of non-empty endoutv6 is fully correct). I provided an empty ("") as endoutv6.pcap.
My expectation was, if I do provide a counters.la file, then the test will not check if endoutv6.pcap or endoutv4.pcap match.

Are you saying, even in the case of providing a counters.lua file as test-criteria as I did above, that : 
if endoutv6.pcap  is NOT empty, then I am not allowed define an empty  endoutv6.pcap as pass-criteria?

As said, I was expecting that if counters-file is provided, then the test will not check the empty endout.pcaps. I guess this is just wrong expectation - so kindly get me corrected here.

```
"ICMP Test - pass-critria out.pcap"
"icmp_snabbvmx-lwaftr-xe1.cfg" "icmp-ipv4-in.pcap" "" "" "HERE THE NON EMPTY CORRECT PCAP must be configured. even if counters.lua is provided"
"icmp.lua"
```


thanks a lot

christian

**Comment by dpino** [comment]
> Are you saying, even in the case of providing a counters.lua file as test-criteria as I did above, that :
> if endoutv6.pcap is NOT empty, then I am not allowed define an empty endoutv6.pcap as pass-criteria?

An empty pcap file as ipv6-output won't work because with the given configuration file and input (icmp-ipv4-in.pcap) the lwAFTR will encapsulate two packets, thus ipv6-output must contain those two packets.

The way the test system works is by passing the input packets to the lwAFTR and comparing the expected output to the output that the lwAFTR has generated. The counters file is compared too to the actual counters file obtained after running the test. To recap the `snabbvmx check` syntax:

```
CONF V4-IN.PCAP V6-IN.PCAP V4-OUT.PCAP V6-OUT.PCAP [COUNTERS.LUA]
```

V4-OUT.PCAP, V6-OUT.PCAP and COUNTERS.LUA are expected output. These output is compared to files stored temporarily in /tmp/endoutv4.pcap, /tmp/endoutv6.pcap and /tmp/counters.lua. These temporal files are the actual output produced by the lwAFTR after running a test. In order for a test to pass, the actual output must match the expected output. So it's not only that the counters file should match, but also the output .pcap files.

If using  icmp-ipv4-in.pcap as it is now, this is how test-env.sh should look like:

```
"ICMP Test - pass-critria out.pcap"
"icmp_snabbvmx-lwaftr-xe1.cfg" "icmp-ipv4-in.pcap" "" "" "icmp-ipv6-out.pcap"
"icmp.lua"
```

And this is icmp-ipv6-out.pcap.

I attach a copy of icmp-ipv6-out.pcap and the counters file (icmp.lua).

[data.zip](https://github.com/Igalia/snabb/files/624154/data.zip)

When running end-to-end.sh should pass this test too:

``` 
$ sudo ./end-to-end.sh
Testing: ICMP Test - pass-critria out.pcap
data/icmp_snabbvmx-lwaftr-xe1.conf: loading compiled configuration from data/icmp_snabbvmx-lwaftr-xe1.o
data/icmp_snabbvmx-lwaftr-xe1.conf: compiled configuration data/icmp_snabbvmx-lwaftr-xe1.o is up to date.
nh_fwd4: cache_refresh_interval set to 0 seconds
nh_fwd4: static next_hop_mac 90:e2:ba:94:2a:bc
nh_fwd6: cache_refresh_interval set to 0 seconds
nh_fwd6: static next_hop_mac 90:e2:ba:94:2a:bc
done
Test passed
```

Let me know how it goes.

**Comment by chrgraf** [comment]
Dear Diego,

Many thanks for this extensive explanation. I am seeing my fault.

Will check it asap.

(and most likely close the issue and create PR for an corrected README.troubleshooting.md)

Thanks

Christian

————————————————————

Christian Graf
Senior Consulting Engineer
Telephone +49 5651/336174
Mobile +49 175/2929 167
cgraf@juniper.net
www.juniper.net

Juniper Networks GmbH
Sitz der Gesellschaft / Registered office: Oskar-Schlemmer-Str. 15, 80807 München
Registergericht / Commercial registry: München, HRB 205571
Geschäftsführer / Directors: Johannes Albers, Stephen Byrne, Terrance Floyd Spidell
_________________________________________________________________________

This email contains material that is confidential. The content of this email is for the sole use of the intended recipient(s).
Any review or distribution by persons other than the intended recipient(s) without the express permission of Juniper Networks is strictly prohibited.
If you are not the intended recipient, please contact the sender and delete/destroy all copies of this email and any related attachments.
Juniper does not guarantee the accuracy or completeness of third party materials or information

————————————————————

**Comment by chrgraf** [comment]
This issue can be closed. The end-to-end test behaves fully correct. Please see Diegos explanation above about the expected behavior.
Rechecked the issue and test behaves as expected.

**Summary**
Even if as check-criteria the counters.lua file is provided, the resulting outv4 and outv6 caps must match as well.
So it is a logical "and" for the all of the three criteria (outv4, outv6 and counters.lua) which must match to pass a check.

thanks

christian
