### ISSUE TITLE
On-a-stick performance testing

### ISSUE THREAD

**Issue by wingo** [Igalia/snabbswitch#565]
As part of the work to get Snabb vMX and the lwAFTR to cooperate, we added support in Snabb for "on-a-stick" operation.  We need to get this performance-tested to ensure that it meets the requirements.

This task is to add an automated benchmark to Hydra that will run the lwAFTR in on-a-stick mode and produce a graph of packet loss versus applied workload, up to 10 Gbps.  The benchmark workload is an IMIX consisting of a 5 64-byte packets, 3 594-byte packets, 1 1500-byte-packet mix in the encapsulation direction, and the same mix in decapsulation except with 40 additional bytes per packet to account for the encapsulation overhead.  We should test this workload in three scenarios: all-encapsulation, all-decapsulation, and mixed.

**Comment by mwiget** [comment]
Cool! Thanks.

**Comment by teknico** [comment]
Implemented by #578, #583, #587.
