### ISSUE TITLE
Add ability to enumerate the set of running Snabb processes

### ISSUE THREAD

**Issue by wingo** [Igalia/snabbswitch#567]
Right now `snabb top` just prints a list of PIDs, with no indication of what those processes are doing.  Now that Snabb applications can have names, probably we should also allow them to declare a short description indicating their function.  In any case "snabb top" should list Snabb programs by name as well as or instead of listing by PID.

**Comment by dpino** [comment]
Example output:

```
$ sudo ./snabb top
Multiple Snabb instances found. Select one:
12369
12365
8231
5741
3063
2929
2808
2696
1050
32511
31862
30956
22653
12640
12633
12512
```

**Comment by dpino** [comment]
This is what `snabb ps` returns now:

```
$ sudo ./snabb ps
12339
12365   [lwaftr2] *
12367
  \- 12369   worker for 12365
12433
12469
12512
```

Running lwaftr command:

```
$ sudo ./snabb lwaftr run -v --name lwaftr2 --reconfigurable \
   --conf lwaftr-migrated.conf --v4 83:00.0 --v6 83:00.1
```

**Comment by wingo** [comment]
The `*` indicates processes that are listening for "snabb config" connections.
