### ISSUE TITLE
Implement "snabb config get-state" for snabb-softwire-v1

### ISSUE THREAD

**Issue by wingo** [Igalia/snabbswitch#568]
We need to implement the get-state command:

```
snabb config get-state -m MODULE ID PATH
```

See https://github.com/snabbco/snabb/issues/987 for an early discussion.  Since then a couple things have changed, notably the relationship between the different processes, and that we're going to first work on our native YANG module rather than the standard IETF one; and that now we understand the relationship between data and schema better, and that paths should be expressed in terms of data, not schema (see #549), and that we have formalized the data grammar better.

Eventually `snabb config` will work by talking to a manager app inside the Snabb process tree, but a first `snabb config get-state` implementation can grovel counter files directly.

**Comment by wingo** [comment]
See also #561.  This one tracks the deliverable.  Probably in this issue/task we should also mention how this feature is tested.

**Comment by tsyesika** [comment]
This has been implemented as of https://github.com/Igalia/snabb/commit/660078799af0cf1649568ce10aa06ef061c26455.

This brings the `snabb config get-state` command which supports [a number of different options](https://github.com/Igalia/snabb/blob/lwaftr/src/program/config/get_state/README.inc). The two required options are the identifier which is either the name of the snabb process or the PID. The other option is the path, the path is a subset of the XPath query language, this allows you to narrow the counters down or even specify specific leaves. The full documentation for the program can be found [here](https://github.com/Igalia/snabb/blob/lwaftr/src/program/config/README.md).

The program works by looking over the YANG schema and finding all the leaf nodes which have `config false;` on them (this specifies they are used for state data, not config data, [see RFC6020 7.19.1](https://tools.ietf.org/html/rfc6020#section-7.19.1)). It then looks for all the counters defined in the specific program and matches them to the leaf names. Any of these counters are then exposed by this program to the user.

## Brief usage

This assumes there is an instance of the lwaftr running.

You need to find the identifier. We have introduced a new program to do this called [ps](https://github.com/Igalia/snabb/blob/lwaftr/src/program/ps/README), this will by default list the name of the program if one exists, or if no name exists, it will list the PID.

```
$ snabb ps
lwaftr1
```

Then to use to this to list all counters, we will use `lwaftr1` as the ID (as found above), and use `/` as the path. The `/` simply specifies all of the state leaves in the schema.
```
$ snabb get-state lwaftr1 /
softwire-state {
  drop-all-ipv4-iface-bytes 0;
  drop-all-ipv6-iface-bytes 0;
  drop-bad-checksum-icmpv4-bytes 0;
  drop-in-by-policy-icmpv4-bytes 0;
  drop-in-by-policy-icmpv6-bytes 0;
  drop-in-by-rfc7596-icmpv4-bytes 0;
  drop-ipv4-frag-disabled 0;
  drop-ipv4-frag-invalid-reassembly 0;
  drop-ipv4-frag-random-evicted 0;
  drop-ipv6-frag-disabled 0;
  drop-ipv6-frag-invalid-reassembly 0;
  drop-ipv6-frag-random-evicted 0;
  drop-misplaced-not-ipv4-bytes 0;
  drop-misplaced-not-ipv6-bytes 0;
  drop-no-dest-softwire-ipv4-bytes 0;
  drop-no-source-softwire-ipv6-bytes 0;
  drop-over-mtu-but-dont-fragment-ipv4-bytes 0;
  drop-over-rate-limit-icmpv6-bytes 0;
  drop-over-time-but-not-hop-limit-icmpv6-bytes 0;
  drop-too-big-type-but-not-code-icmpv6-bytes 0;
  drop-ttl-zero-ipv4-bytes 0;
  drop-unknown-protocol-ipv6-bytes 0;
  hairpin-ipv4-packets 0;
  in-ipv4-frag-needs-reassembly 0;
  in-ipv4-frag-reassembled 0;
  in-ipv4-frag-reassembly-unneeded 73,603,098;
  in-ipv4-packets 73,603,098;
  in-ipv6-frag-needs-reassembly 0;
  in-ipv6-frag-reassembled 0;
  in-ipv6-frag-reassembly-unneeded 73,602,996;
  in-ipv6-packets 73,602,894;
  memuse-ipv4-frag-reassembly-buffer 463,571,780;
  memuse-ipv6-frag-reassembly-buffer 464,727,376;
  out-icmpv4-packets 0;
  out-icmpv6-packets 0;
  out-ipv4-frag 0;
  out-ipv4-frag-not 73,602,792;
  out-ipv4-packets 73,602,894;
  out-ipv6-frag 0;
  out-ipv6-frag-not 73,603,098;
  out-ipv6-packets 73,603,098;
}
```

To just see the value of one of these, the explicit path to the counter can be specified:
```
$ snabb config get-state lwaftr /softwire-state/in-ipv4-frag-reassembly-unneeded/
73,603,098
```

**Comment by wingo** [comment]
After some bug fixes by @xray7224 there are more counters now and the output looks like this:

```
[wingo@snabb2:~/snabb/src]$ sudo ./snabb config get-state lwaftr /
softwire-state {
  drop-all-ipv4-iface-bytes 0;
  drop-all-ipv4-iface-packets 0;
  drop-all-ipv6-iface-bytes 11550;
  drop-all-ipv6-iface-packets 21;
  drop-bad-checksum-icmpv4-bytes 0;
  drop-bad-checksum-icmpv4-packets 0;
  drop-in-by-policy-icmpv4-bytes 0;
  drop-in-by-policy-icmpv4-packets 0;
  drop-in-by-policy-icmpv6-bytes 0;
  drop-in-by-policy-icmpv6-packets 0;
  drop-in-by-rfc7596-icmpv4-bytes 0;
  drop-in-by-rfc7596-icmpv4-packets 0;
  drop-ipv4-frag-disabled 0;
  drop-ipv4-frag-invalid-reassembly 0;
  drop-ipv4-frag-random-evicted 0;
  drop-ipv6-frag-disabled 0;
  drop-ipv6-frag-invalid-reassembly 0;
  drop-ipv6-frag-random-evicted 0;
  drop-misplaced-not-ipv4-bytes 0;
  drop-misplaced-not-ipv4-packets 0;
  drop-misplaced-not-ipv6-bytes 11550;
  drop-misplaced-not-ipv6-packets 21;
  drop-no-dest-softwire-ipv4-bytes 0;
  drop-no-dest-softwire-ipv4-packets 0;
  drop-no-source-softwire-ipv6-bytes 0;
  drop-no-source-softwire-ipv6-packets 0;
  drop-out-by-policy-icmpv4-packets 0;
  drop-out-by-policy-icmpv6-packets 0;
  drop-over-mtu-but-dont-fragment-ipv4-bytes 0;
  drop-over-mtu-but-dont-fragment-ipv4-packets 0;
  drop-over-rate-limit-icmpv6-bytes 0;
  drop-over-rate-limit-icmpv6-packets 0;
  drop-over-time-but-not-hop-limit-icmpv6-bytes 0;
  drop-over-time-but-not-hop-limit-icmpv6-packets 0;
  drop-too-big-type-but-not-code-icmpv6-bytes 0;
  drop-too-big-type-but-not-code-icmpv6-packets 0;
  drop-ttl-zero-ipv4-bytes 0;
  drop-ttl-zero-ipv4-packets 0;
  drop-unknown-protocol-icmpv6-bytes 0;
  drop-unknown-protocol-icmpv6-packets 0;
  drop-unknown-protocol-ipv6-bytes 0;
  drop-unknown-protocol-ipv6-packets 0;
  hairpin-ipv4-bytes 0;
  hairpin-ipv4-packets 0;
  in-ipv4-bytes 1282763309850;
  in-ipv4-frag-needs-reassembly 0;
  in-ipv4-frag-reassembled 0;
  in-ipv4-frag-reassembly-unneeded 2332297027;
  in-ipv4-packets 2332296927;
  in-ipv6-bytes 1282763870300;
  in-ipv6-frag-needs-reassembly 0;
  in-ipv6-frag-reassembled 0;
  in-ipv6-frag-reassembly-unneeded 2332297967;
  in-ipv6-packets 2332297946;
  ingress-packet-drops 0;
  memuse-ipv4-frag-reassembly-buffer 463571780;
  memuse-ipv6-frag-reassembly-buffer 464727376;
  out-icmpv4-bytes 0;
  out-icmpv4-packets 0;
  out-icmpv6-bytes 0;
  out-icmpv6-packets 0;
  out-ipv4-bytes 1189471952460;
  out-ipv4-frag 0;
  out-ipv4-frag-not 2332297946;
  out-ipv4-packets 2332297946;
  out-ipv6-bytes 1376055186930;
  out-ipv6-frag 0;
  out-ipv6-frag-not 2332296880;
  out-ipv6-packets 2332296927;
}


[wingo@snabb2:~/snabb/src]$ sudo ./snabb config get-state lwaftr /softwire-state/out-ipv4-packets
2372269690

```
