### ISSUE TITLE
Measure impact of binding table updates on data-plane performance

### ISSUE THREAD

**Issue by wingo** [Igalia/snabbswitch#573]
When the data plane is operating at full load, both in bump-in-the-wire, 550 bytes/packet workloads and on-a-stick IMIX workloads, we need to make sure that we can update the binding table without causing packet drops.  To this end we need to create a test rig consisting of three components: one, a lwaftr; two, a load generator that measures and records packet loss; three, a "snabb config" workload that uses the listen interface to add and remove entries to the binding table.  To allow the packet loss characteristics to be measured, we should make these changes to softwires that are not seeing any traffic in the test workload.  The target is 1000 changes/second without packet loss.

Ideally we should express this test as a hydra job.  Maybe we don't have to run this hydra job on every commit, but we should be able to run it manually.

**Comment by chrgraf** [comment]
Hi Andy,

One question please. I thought that snabb required a restart to use a modified binding-table.
Such restart, even as done very fast, was leading in the past to always drop packets when changing the binding-table.

Can you please let me know what changed to update lwaftr's binding-table on the fly with no drops for valid binding-entries?

Thanks

Christian

---

Christian Graf
Senior Consulting Engineer
Telephone +49 5651/336174
Mobile +49 175/2929 167
cgraf@juniper.net
www.juniper.net

Juniper Networks GmbH
Sitz der Gesellschaft / Registered office: Oskar-Schlemmer-Str. 15, 80807 München
Registergericht / Commercial registry: München, HRB 205571
Geschäftsführer / Directors: Johannes Albers, Stephen Byrne, Terrance Floyd Spidell

---

This email contains material that is confidential. The content of this email is for the sole use of the intended recipient(s).
Any review or distribution by persons other than the intended recipient(s) without the express permission of Juniper Networks is strictly prohibited.
If you are not the intended recipient, please contact the sender and delete/destroy all copies of this email and any related attachments.
Juniper does not guarantee the accuracy or completeness of third party materials or information

**Comment by wingo** [comment]
Hi @chrgraf, this is a milestone bug for our use when planning future releases.  We will be adding support for changing the binding table without dropping packets.  Further details to come later.

**Comment by chrgraf** [comment]
Hi Andy,

Thanks for quick feedback! I got it.

Thanks

Christian

---

Christian Graf
Senior Consulting Engineer
Telephone +49 5651/336174
Mobile +49 175/2929 167
cgraf@juniper.net
www.juniper.net

Juniper Networks GmbH
Sitz der Gesellschaft / Registered office: Oskar-Schlemmer-Str. 15, 80807 München
Registergericht / Commercial registry: München, HRB 205571
Geschäftsführer / Directors: Johannes Albers, Stephen Byrne, Terrance Floyd Spidell

---

This email contains material that is confidential. The content of this email is for the sole use of the intended recipient(s).
Any review or distribution by persons other than the intended recipient(s) without the express permission of Juniper Networks is strictly prohibited.
If you are not the intended recipient, please contact the sender and delete/destroy all copies of this email and any related attachments.
Juniper does not guarantee the accuracy or completeness of third party materials or information

**Comment by wingo** [comment]
To test this, you run a lwaftr.  Say it's running and named "lwaftr".  For this example:

```
sudo ./snabb lwaftr run --name lwaftr --reconfigurable --cpu 4 --conf program/lwaftr/tests/data/icmp_on_fail.conf --v4 03:00.0 --v6 03:00.1
```

Now run a loadtest:

```
sudo numactl -m 1 taskset -c 9 ./snabb lwaftr loadtest -D 5 --program=ramp_down -b 9.2e9 -s 1e5 program/lwaftr/tests/benchdata/ipv4-0550.pcap "NIC 0" "NIC 1" 83:00.0 program/lwaftr/tests/benchdata/ipv6-0550.pcap "NIC 1" "NIC 0" 83:00.1
```

Now we create a script of commands to add and remove softwires.  For example:

```json
{"id":"add","verb":"add","path":"/softwire-config/binding-table/softwire",
 "value":"{ ipv4 178.79.150.1; psid 1; b4-ipv6 200:01:20:30:40:50:60:128; }"}
{"id":"remove","verb":"remove",
 "path":"/softwire-config/binding-table/softwire[ipv4=178.79.150.1][psid=1]"}
```

Copy that like 100 or 1000 times in a file (say `commands.json`).  Then pass it to "snabb config bench":

```
$ while sleep 1; do sudo ./snabb config bench lwaftr ../../commands4.json ; done
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr
Issued 378 commands in 0.23 seconds (1673.00 commands/s)
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr
Issued 378 commands in 0.22 seconds (1701.78 commands/s)
...
```

The "w" entries indicate where "snabb config bench" was writing a request and "r" indicates when it read a response.  It will write requests while there is room in the pipe to `snabb config listen`, which by default can fill up 64 KB on modern Linux systems.  Then it will read responses to buffered writes, then buffer some more writes, and so on.  As you can see the rate in this example is about 1700 commands/s.

Now check the loadtest results.  In my tests I see no drops at 1.75 MPPS FDX; I see some drops around 2 MPPS though.
