### ISSUE TITLE
Handling foreign YANG schemas design document

### ISSUE THREAD

**Issue by wingo** [Igalia/snabbswitch#608]
Usually operators want to work against network devices described by standard YANG schemas.  However when you go to build a data plane, it inevitably has different functionality compared to any given standard schema.  Because you need to support the standard schema also, that "native" schema ends up being a superset of the standard schema.

It's also possible that an operator might want to see a device from many perspectives.  For example there might be one schema describing the NICs in use and their L2 addresses, another describing routing tables, another measuring CPU usage, and so on.

This issue aims to sketch a solution to this problem for Snabb, with specific reference to the case of the lwAFTR which has a native schema, `snabb-softwire-v1`, and for which we would like to add support for `ietf-softwire`.  Let's call any non-native schema a *foreign* schema.

A foreign schema must be a subset of the native schema, for reasons described above.  Therefore an operation in terms of a foreign schema can be translated to an operation in terms of a native schema.  That's the backbone of our strategy: just one main configuration, described by the native schema, and translators between operations in terms of foreign schemas.

There is a generic way to query an existing configuration from a foreign schema, then:
- Take the current native configuration and translate it to a foreign configuration.  (This is possible because the foreign schema is a subset of the native schema.)
- Query over that foreign configuration.

The result of the first step can be cached, and only recomputed when the current native configuration changes.  Additionally when updating the current configuration from that same foreign schema, we can sometimes update both the current native configuration and the current foreign configuration in an O(change size) way, to avoid the future O(configuration size) cost of translating the native configuration to the foreign configuration.

Relatedly then the generic way to update an existing configuration would be:
- Traslate the foreign update request (`set`, `add`, `remove`) to equivalent operations on the native configuration, and apply them
- Make corresponding updates to the current foreign configuration.  Mark all other foreign configurations (if any) as being out of date and needing recomputation.

We need to add a hook that will cause an update to the current configuration via the native schema to invalidate any cached current foreign configuration.

OK I think that's it.  Going to give it a go this afternoon.

**Comment by plajjan** [comment]
Does it make sense to put the translation functionality in sysrepo instead? It's a generic issue so a generic solution could benefit many and also help in maintaining it by not putting everything in Snabb.

**Comment by wingo** [comment]
Good question @plajjan!  I assumed that this wasn't a possibility.  To me, Snabb sounds about the right place because the specifics of the ietf-softwire schema and how it maps to snabb-softwire seem to be the domain of the lwaftr itself more than a generic netconf agent -- but I dunno, either way could work.

For now I will implement in Snabb as that's the bit that I control and can test :)  But if in the future we determine that's not the right thing, we can move that code and functionality to sysrepo instead.

**Comment by wingo** [comment]
Closing issue as the code landed earlier this week.
