### ISSUE TITLE
Test "snabb config" facility

### ISSUE THREAD

**Issue by wingo** [Igalia/snabbswitch#615]
The new "snabb config" facility needs testing. :)

To test, run:

```
$ make
$ sudo SNABB_LEADER_VERBOSE=1 ./snabb lwaftr bench \
    --name lwaftr --bench-file /dev/stdout --reconfigurable \
    program/lwaftr/tests/data/icmp_on_fail.conf \
    program/lwaftr/tests/benchdata/ipv4-0550.pcap \
    program/lwaftr/tests/benchdata/ipv6-0550.pcap
```

The "SNABB_LEADER_VERBOSE" bit lets you know a bit more about when things are changing.

Then to test with "snabb config", in another terminal, do:

```
$ sudo ./snabb config get lwaftr /
$ sudo ./snabb config get lwaftr / | sudo ./snabb config set lwaftr /
```

Try different paths, try add/remove, try add/remove on weird paths, etc.  As you find bugs (and you will), please file them! Anything that causes the data plane to crash or have bad state that can't be recovered from is high priority; a bad error message is low priority.

**Comment by teknico** [comment]
Lower-priority problems are recorded in other issues. This one includes some doc fixes in #643.
