### ISSUE TITLE
"snabb lwaftr query" should support names

### ISSUE THREAD

**Issue by wingo** [Igalia/snabbswitch#623]
Right now I think it just works for pids.

**Comment by dpino** [comment]
This was requirement in SnabbVMX too so I implemented an ad-hoc mechanism to query a process by name. The name is stored as a counter in `nic/id`. SnabbVMX can be launched passing an id argument, which value is stored in this counter. Example:

```
sudo ./snabb snabbvmx --id xe0 ...
```

So when properly implementing this feature, it would be ideal to remove this ad-hoc support and double check SnabbVMX keeps working.
