### ISSUE TITLE
We ship a "snabb-lwaftr" binary from which "snabb config" is inaccessible

### ISSUE THREAD

**Issue by wingo** [Igalia/snabbswitch#634]
We ship a "snabb-lwaftr" binary in our releases.  However we can't get to "snabb config" from this binary.  What should we do?  Options would be to ship "snabb" but that could be confusing ("what binary is this?").  Or we ship two binaries maybe.  What to do?

**Comment by dpino** [comment]
My two cents: to ship two commands but only binary. We keep snabb-lwaftr binary and snabb-config is a link to snabb-lwaftr. That would allow to execute "snabb config".

**Comment by wingo** [comment]
I have reports that users are used to switching back and forth anyway because of git, and with git you just have "snabb". In that case let's ship "snabb" and then a symlink from snabb-lwaftr to snabb to keep old scripts and documentation working.  Sound about right to you @dpino ?

**Comment by dpino** [comment]
SGTM.

**Comment by kbara** [comment]
SGTM too

**Comment by wingo** [comment]
Fixed in #649.
