### ISSUE TITLE
Address Kristian's feedback on the YANG model

### ISSUE THREAD

**Issue by wingo** [Igalia/snabbswitch#636]
See https://github.com/Igalia/snabb/issues/510#issuecomment-259973663.

**Comment by dpino** [comment]
For those PRs that don't pass CI, it's necessary to close them and open a new PR like the original one but including a fix to make it pass CI. That's the case of #679, which was closed in favour of #688.

**Comment by wingo** [comment]
I believe all issues here have been addressed.  Thanks @plajjan for your feedback here!
