### ISSUE TITLE
Fix "snabb config" error reporting

### ISSUE THREAD

**Issue by wingo** [Igalia/snabbswitch#637]
Currently the leader doesn't ship errors back to the "snabb config" invoker, which is a bit irritating and leaves the user with a pretty scary traceback about a short read.  This needs to be improved; the user should see a nice error and a non-zero exit code.

**Comment by dpino** [comment]
Addressed in #685. I keep the ticket open because I don't know if there's something else to.

**Comment by tsyesika** [comment]
This has been addressed as of PR #685 as @dpino said. This currently works by wrapping the calls in the leader in a `pcall` and if there is an error send that back with the error message. This does not allow for a traceback, I'm not sure if that's desired or not right now.

I'm going to close this, another issue can be opened if we decide we want to add traceback support to the error reporting.
