### ISSUE TITLE
Main process should use less CPU

### ISSUE THREAD

**Issue by wingo** [Igalia/snabbswitch#652]
Right now the main process does a busy wait.  It should instead make the listener have a timeout for accepting new connections or reading new data I guess.  Anyway it should use less CPU.

**Comment by teknico** [comment]
More context from an email by @dpino:

> When running `lwaftr run --reconfigurable` (this starts the lwaftr with a leader and a follower), the leader is run in busywait mode, so it takes 100% of the core it is assigned to.
> 
> The leader doesn't need to take control full-control of a core, since the ratio of incoming commands won't be that high to make this worth. It could even be desirable to pin the leader to a kernel-managed core.

**Comment by teknico** [comment]
Same problem is present when running the `lwaftr bench --reconfigurable` command, fixed in #738.
