### ISSUE TITLE
Let SnabbAFTR manage the list of br-addresses

### ISSUE THREAD

**Issue by plajjan** [Igalia/snabbswitch#683]
The YANG model currently contains a list of softwires and a leaf-list of br-addresses. software/br references into the br-address leaf-list using a zero-based index. This is not very YANGy at all and puts the job of coming up with these references on the NETCONF client.

I don't see the point of this and to me this feels like it belongs as an internal function of the SnabbAFTR.

I suggest that we remove the leaf-list br-address from the YANG model, remove software/br and instead add software/br-address as an IPv6 address. I understand the SnabbAFTR needs the br-addres list internally, but it would just be a matter of creating entries in the list implicitly based on software/br-address.

Have I completely missed something? Would such a change break something?

**Comment by plajjan** [comment]
This was originally part of #636 too.

**Comment by plajjan** [comment]
@lwaftr-igalia comment please. I would really like to avoid having to implement this in our provisioning software because it breaks its stateless nature. As I'm sure you are aware, we want to put the SnabbAFTR, including NC/YANG, in the pilot rather soon (right about last year actually) so I would like this issue to receive some love ;)

**Comment by kbara** [comment]
The two members of the team who know this stuff best are on vacation for another couple of days, but I'll bring it up with them on Friday/Monday.

**Comment by plajjan** [comment]
@kbara ok, thanks! :)

**Comment by wingo** [comment]
This one is fixed in the lwaftr branch, yay!  Thanks @xray7224 :)
