### ISSUE TITLE
Snabb config with bogus field gives a traceback

### ISSUE THREAD

**Issue by kbara** [Igalia/snabbswitch#707]
# ./snabb config set -s snabb-softwire-v1 24108 "/softwire-config/internal-interface/reassembly-max-fragments-per-packet" "332167"
lib/yang/path.lua:216: Struct has no field named 'reassembly-max-fragments-per-packet'.
stack traceback:
        core/main.lua:149: in function <core/main.lua:147>
        [C]: in function 'error'
        lib/yang/path.lua:216: in function 'compute_getter'
        lib/yang/path.lua:233: in function 'f'
        lib/yang/util.lua:115: in function 'path_resolver'
        program/config/common.lua:30: in function 'path_grammar'
        program/config/common.lua:35: in function 'data_parser'
        program/config/common.lua:71: in function 'parse_command_line'
        program/config/set/set.lua:7: in function 'run'
        program/config/config.lua:23: in function 'run'
        core/main.lua:67: in function <core/main.lua:43>
        [C]: in function 'xpcall'
        core/main.lua:211: in main chunk
        [C]: at 0x00454440
        [C]: in function 'pcall'
        core/startup.lua:3: in main chunk
        [C]: in function 'require'
        [string "require "core.startup""]:1: in main chunk

**Comment by wingo** [comment]
Verified:

```
$ sudo ./snabb config set foo /softwire-config/internal-interface/reassembly-max-fragments-per-packet 332167
lib/yang/path.lua:247: Struct has no field named 'reassembly-max-fragments-per-packet'.
```

**Comment by wingo** [comment]
I.e., no backtrace, but no nice error either.
