### ISSUE TITLE
Add name leaf to snabb-softwire supporting modification and discovery of lwaftr's name

### ISSUE THREAD

**Issue by tsyesika** [Igalia/snabbswitch#737]
This issue is to add support for a `name` leaf to the snabb-softwire-v1 YANG configuration schema. This will be used to set the name of an instance of the lwaftr. There will be two mechanisms to do this, the current method which is to use the command line flag `--name` and the setting of the leaf in the configuration. The order of precedence is as follows:

1. On an already running instance, a `snabb config set` will override any name given by any other previous means providing the name is available (If the name is already taken, an error will be produced and the previous name - if there was one, will continue to be used). 
2. If `--name`is specified on the command line this will be used, overriding any name specified in the config file (allowing instances using the same config, even if the name is specified)
3. If no `--name` parameter is specified it will try to use the config file's name leaf. (if another instance exists with the same name, it will result in an error upon starting)
4. If no name exists in either config file or `--name` parameter it will run the lwaftr without a name, as per usual.

The name leaf will **not** be mandatory meaning nameless instances can still be used. This change allows for the discovery of an instances name by doing a `snabb config get` query against the leaf. It also allows for setting or re-naming of instances by using `snabb config set`, modifying an instances name - this previously was not possible. The `ietf-softwire` schema already has a name parameter so this will also provide a translator to and from `ietf-softwire` allowing for name to be set and exposed there too.

This will also fix #701 which relies on this functionality to exist, however this feature set more general and broader than that issue called for, hence a new issue outlining the proposal.

**Comment by wingo** [comment]
And I guess a snabb config set will override anything?  SGTM, thanks for the design doc :)

**Comment by tsyesika** [comment]
Yes indeed. Providing the name isn't taken `snabb config set` will modify any existing name that may have been specified by any other means. If the name is taken, a snabb config set will produce an error message explaining such.

(I'll modify the issue so we have a single, correct, comprehensive version of how this will work until the docs are written).

**Comment by tsyesika** [comment]
I think this can be closed as it's been merged into the `lwaftr` branch.
