### ISSUE TITLE
Python infrastructure for integration tests

### ISSUE THREAD

**Issue by teknico** [Igalia/snabbswitch#749]
As recently discussed on the team, and [approved](https://github.com/snabbco/snabb/issues/1106) by upstream, we are going to write integration tests in Python, in addition to shell scripts.

### Python version

We are going to use Python 3, not Python 2.

Python 3.0 was released [in 2008](https://www.python.org/dev/peps/pep-0361/#release-schedule), and its current version [is 3.6](https://www.python.org/dev/peps/pep-0494/#release-schedule).

Python 2.7.0, the last v. 2 minor version, was released [in 2010](https://www.python.org/dev/peps/pep-0373/#release-schedule), and its end of life [is in 2020](https://www.python.org/dev/peps/pep-0373/#maintenance-releases).

The migration of the ecosystem to Python 3 is [almost complete](https://python3wos.appspot.com/), and we will not be needing additional libraries anyway (with one exception, see below).

The Python 3 interpreter has been available for years [on NixOS](http://nixos.org/nixpkgs/manual/#interpreters), [on Ubuntu](http://packages.ubuntu.com/search?keywords=python3), and on most other platforms.

Both Ubuntu 14.04 and NixOS include at least Python 3.4, therefore we will be able to use the `enum` and `pathlib` libraries [introduced in v. 3.4](https://docs.python.org/3/whatsnew/3.4.html#whatsnew-enum).

Also, implicit namespace packages ([introduced in Python 3.3](https://docs.python.org/3/whatsnew/3.3.html#pep-420-implicit-namespace-packages)) will avoid unsightly `__init__.py` files all over the place.

Last but not least, Python 3 is better overall. :-)

### Test framework

We are going to use the standard [`unittest`](https://docs.python.org/3/library/unittest.html) library. Other testing frameworks are available, but they don't add enough value for our use case to justify adding a dependency.

### Subprocess handling

The standard `subprocess` library is [not easy to use](https://docs.python.org/3/library/subprocess.html#replacing-older-functions-with-the-subprocess-module), and feature incomplete.

We are going to use the [`sh`](http://amoffat.github.io/sh/) library, which handles gracefully most of our use cases with a clear and terse syntax. It has been around for years and is implemented by [one single file](https://github.com/amoffat/sh/blob/master/sh.py) that we are adding to our repo, to avoid having dependencies other than the Python 3 interpreter.

### Code structure

Integration tests are run by the `make test` command, which calls all `selftest.sh` shell scripts in the codebase. We will have a single entry point for all lwAftr Python tests, located in the `src/program/lwaftr/tests/selftest.sh` script.

A single entry point reduces setup code duplication and avoids the overhead of starting up the Python interpreter multiple times. We will still be able to run tests in specific subdirectories.

Furthermore, Python integration tests will be confined to the `src/program/lwaftr/tests/`, to ease human and automated discoverability.

### Security

Snabb commands executed in integration tests need root privileges. However, tests as a whole do not have to be run under `sudo` anymore: individual commands are run under `sudo` as needed.

The user under which tests are executed still has to be added to `/etc/sudoers` with a NOPASSWD clause, to enable unattended execution.

**Comment by teknico** [comment]
Hrmpf. Spoke too soon with regard to not having to pepper all test directories with `__init__.py` files: apparently recursive test discovery in namespace packages is [currently broken](https://bugs.python.org/issue23882). So peppering it is, for now.

**Comment by teknico** [comment]
This is now in place with #750, #751 and subsequent changes (notably #763).

**Comment by kbara** [comment]
Fantastic, thank you!
