### ISSUE TITLE
Reassemble incoming IPv4 fragments

### ISSUE THREAD

**Issue by kbara** [Igalia/snabbswitch#78]

**Comment by aperezdc** [comment]
Provided that I implemented the IPv4 fragmentation, I'll go ahead an implement this. I'm assigning the issue to me, and once the reassembly code is ready, we can bounce the issue back to you for integration.

**Comment by andywingo** [comment]
What is the status here @aperezdc? :)

**Comment by aperezdc** [comment]
@andywingo: The functionality has been implemented (see PR #87), and just today I have updated the code to also work well after the refactor of the 802.1Q VLAN handling.

**Comment by aperezdc** [comment]
I have to update later today PR #87 with the cleanups suggested in the code review of PR #116 (which contains the backport of this for the `lwaftr_nutmeg` branch), and then it will be ready for merging.

**Comment by aperezdc** [comment]
PR #87 is now already merged, and I have posted PR #120 with the cleanups suggested in PR #116.

**Comment by aperezdc** [comment]
Now that PRs #87 and #120 are merged, the remaining bit is to add the needed calls to `fragmentv4.reassemble_ipv4()` in the lwAFTR code.

**Comment by kbara** [comment]
@aperezdc do you want to do that (plus the fragment caching, IPv6-style), or should I? :)

**Comment by aperezdc** [comment]
@kbara: I'm working on it.

**Comment by aperezdc** [comment]
I have posted a first pass at the code in PR #135, and right now @kbara is going over the code before merging it. Also, I found a leak in the existing fragment cache for IPv6, which is handled in issue #137.

**Comment by kbara** [comment]
This is merged and backported and tested, so I believe this is done.
