### ISSUE TITLE
Write the "lwaftr transient" selftest

### ISSUE THREAD

**Issue by teknico** [Igalia/snabbswitch#788]
Write the `snabb lwaftr transient` subcommand selftest.

**Comment by teknico** [comment]
The `transient` subcommand seems to perform a subset of the work of the `loadtest` one. It's only used by `src/program/lwaftr/doc/benchmarks-v1.0/Makefile`. Is it still useful, or can we remove it? If the latter, what about the 1.0 benchmarks?

**Comment by teknico** [comment]
@dpino, @wingo, any thoughts?

**Comment by dpino** [comment]
No longer needed since `transient` is an old version of `loadtest`. Fixed by #951.
