### ISSUE TITLE
Clean up 802.1q tagging support

### ISSUE THREAD

**Issue by kbara** [Igalia/snabbswitch#79]
The current code re-assigns constants and assumes all packets are tagged/untagged based on a configuration variable.

**Comment by andywingo** [comment]
Closing as done in https://github.com/Igalia/snabbswitch/pull/105.

**Comment by kbara** [comment]
Well, it's cleaner, but there'll definitely be more work going into it over the next while; several bugs depend on that.

**Comment by andywingo** [comment]
OK :) So let's retitle this bug to make it actionable.  Is it just a question of cleanups, or are there correctness issues, and if so which issues?  Correctness issues are 1.1 material, cleanups probably not.

**Comment by kbara** [comment]
They're linked. I want to centralize our header handling. For 1.1, it's going to be very C-style, like the lwaftr's fast path. For a later release, I'd like to make it more lib.protocol style again, because that's a much safer style of programming. Right now, we're using a mix, part of which supports vlans and part of which doesn't.

**Comment by kbara** [comment]
https://github.com/Igalia/snabbswitch/pull/121 addresses the core of it, though various edges can be cleaned further, as discussed with @aperezdc .

**Comment by kbara** [comment]
I'm going to close this now. It still depends on a configuration variable, and a further issue can be opened if that becomes an issue at any point. Vlan handling is significantly better now, both internally and at the configuration level.
