### ISSUE TITLE
Design of next lwaftr YANG model

### ISSUE THREAD

**Issue by wingo** [Igalia/snabbswitch#801]
When you decide to use lightweight 4-over-6 as your IPv4 solution, you buy into the idea of a horizontally scalable bank of lwAFTR instances.  You will have many servers, and you'll need to configure each one with the binding table and the various parameters like ingress filters and vlans and what-not.

With the current model, you actually have to configure each interface separately as well -- one server with N interfaces appears to the network configuration system as N servers, in a way.  This is unnecessary complexity.  It would be nicer if we could configure a bank of lwAFTR instances on a single server as a single `snabb config` endpoint.  All instances would share the same binding table.  Each instance would have its own next hop configuration and state.

It would be possible to use more "standard" components for interface configuration and state data, such as https://tools.ietf.org/html/rfc7223 and maybe even https://tools.ietf.org/html/rfc7277.  But for this we need #798, #799, and #800.  Perhaps that is too much and we should punt.  Or, perhaps we should timebox it and see where we get.

[This issue is still in draft state.  Pending to develop an actual yang model.]

**Comment by wingo** [comment]
Some resources for better designing YANG models:

https://tools.ietf.org/html/rfc6087

https://github.com/openconfig/public/blob/master/doc/openconfig_style_guide.md

**Comment by wingo** [comment]
/me cc's @xray7224 & @plajjan just fyi

**Comment by plajjan** [comment]
I've imagined this weaves into RSS support so we keep the single binding table but there might be many worker processes behind the scenes. As you point out the interface config would need to change.

**Comment by dpino** [comment]
Fixed in https://github.com/Igalia/snabb/pull/821
