### ISSUE TITLE
How should we program the RSS redirection table in VMDq mode for intel_mp?

### ISSUE THREAD

**Issue by takikawa** [Igalia/snabbswitch#808]
This is an issue to brainstorm solutions for programming the RSS redirection table for the `intel_mp` driver when it's in VMDq mode. Sorry it's kind of long, but I figured I should try to include enough context to understand what's going on. (CC @teknico)

To recap, VMDq lets you do queue assignment on the NIC to several "virtual functions" (for us it's separate Snabb app instances) based on MAC addresses or VLAN tags. If you look in the datasheet in section 7.1.2.2 (pg. 286), you can see the queuing schemes that are available in table 7-3.

Essentially, you can assign queues based on either 16, 32, or 64 "pools" which each may have multiple queues using RSS (or DCB, but we can ignore that). With RSS enabled, you can have up to either 2 or 4 RSS queues depending on how many pools you choose.

How RSS works is that you compute a hash function over the packet header (the header 5-tuple) and use the resulting hash value to index into an RSS redirection table. The value at that index indicates the queue that will be assigned for the incoming packet. This value may be masked out to some number of bits depending on how you use it (explained below).

By programming the table, you can get fine-grained control over how to assign the hash space to the queues (e.g., you could assign all hashes to one queue, or 80% of them to one queue and evenly for the rest, etc.). In practice, the upstream `intel_mp` driver evenly assigns the mapping in an alternating fashion among all enabled queues (i.e., traffic is split evenly among RSS queues).

When VMDq mode is turned on, the queue number obtained from the table mapping is masked to match however many RSS queues are enabled per pool (masked to either 1 or 2 bits). Furthermore, the RSS redirection table is shared among all the pools.

This means you can get a situation in which you have two pools enabled (A and B) which have, respectively, 3 queues enabled and 4 queues enabled. Ideally, you might want to be able to set a redirection table for A that redirects to just 3 queues evenly and similarly with 4 queues for B. But you can't do that since you only have a single table.

(note that if a queue is not enabled but is chosen in queue assignment, packets going to it are just dropped---see page 172)

If you program the shared table based on 3 queues for pool A, you won't utilize one of the queues in pool B. If you program the table based on the 4 queues for pool B, you will drop some packets in pool A for the extra queue. The current behavior, which is to program it based on all enabled queues, will have an uneven distribution in pool B and drop some packets in pool A.

Maybe one solution might be to program the table for 1, 2, or 4 queues in every pool (based on a config option) and require that the user enable at least that many queues to each pool (or else risk losing some packets). Or we could keep the existing behavior and just suggest that users enable the same number of queues to each pool.

Anyhow, any thoughts? I'm not sure I've explained the problem clearly enough, so let me know if it's unclear (it might be better to explain in person with diagrams, perhaps next week). It's also possible that I've misunderstood the datasheet, so let me know if there's an error in my reasoning on how this works.

**Comment by teknico** [comment]
> Maybe one solution might be to program the table for 1, 2, or 4 queues in every pool (based on a config option) and require that the user enable at least that many queues to each pool (or else risk losing some packets).

If the table is programmed for two queues and the user enables four of them, wouldn't two queues in the user pool remain unused?

> Or we could keep the existing behavior and just suggest that users enable the same number of queues to each pool.

This sounds sensible. It's a hardware limitation after all. And I'd require that, rather than just suggesting it. :-)

**Comment by takikawa** [comment]
> If the table is programmed for two queues and the user enables four of them, wouldn't two queues in the user pool remain unused?

Yes, the idea was to specify a config option like `vmdq_rss = 2` or something and program it to use the first two queues in every pool or something like that. So if they want to use 4 queues, they could set it to 4 (but then all pools should use 4).

> This sounds sensible. It's a hardware limitation after all. And I'd require that, rather than just suggesting it. :-)

Ok. I think it's tricky to actually enforce this condition programmatically though, because the driver app instances aren't aware of how many queues will be used eventually and they aren't created all at once necessarily.
