### ISSUE TITLE
Extend `snabb-softwire-v2` to support multiple processes

### ISSUE THREAD

**Issue by wingo** [Igalia/snabbswitch#820]
This is a subtask of #819 to update `snabb-softwire-v2`, and adapt the lwAFTR accordingly, but without implementing the multiple-process machinery.

The `/softwire-config/binding-table` will remain as it is.

The `/softwire-config/internal-interface` and `/softwire-config/external-interface` components will need reworking to separate the parts that are always the same between the different processes (e.g. icmp error policy) and the parts that might differ (e.g. MAC address / next hop / etc).

Then we will have to incorporate such details as PCI addresses, L2 and L3 configuration (self and next-hop MAC and IP addresses), and possibly cores, and also counters into per-instance lists keyed on, oh, I don't know.

This step doesn't have to support RSS yet but it should be written thinking about RSS.  The idea would be, our goal is to allow one main lwAFTR process to manage a fleet of workers that each service a different interface.  In the future we can consider multiple workers servicing different RSS queues on the same interface.

**Comment by wingo** [comment]
I started looking into this and started down the rat-hole of seeing what IETF standards could be useful for us, since the IETF standards already cover a lot of the configuration that we need.  Unfortunately it's too complicated for the time that we have available; see #801.  I would avoid IETF models for now and just migrate our existing `internal-interface` etc to the multi-process world, separating the general policy from the specific configurations.

**Comment by tsyesika** [comment]
I think this is done as of PR #821.
