### ISSUE TITLE
Add Changelog

### ISSUE THREAD

**Issue by dpino** [Igalia/snabbswitch#83]
We should have a Changelog so it's easier to keep track of new feature additions. When someone adds a new feature, should also add a small description to the Changelog. Initially, the Changelog should contain a description of the main features of the lwaftr v1.0.

**Comment by aperezdc** [comment]
Just an idea: using the “[keepachangelog](http://keepachangelog.com/)” format. It's Markdown, so it renders nicely (e.g. in GitHub), and being a speficied format, [tooling](https://github.com/olivierlacan/keep-a-changelog/issues/67) can be made (and some tools exist already).

**Comment by dpino** [comment]
+1 using keepachanglog format.

**Comment by kbara** [comment]
We now have a changelog. @dpino , think we can close this issue?
