### ISSUE TITLE
Add "xpath" style of output for "snabb config get" and "snabb config get-state"

### ISSUE THREAD

**Issue by wingo** [Igalia/snabbswitch#837]
Sysrepo integration would apparently be easier if we add the ability for "snabb config get" and "snabb config get-state" to produce output in "xpath format": basically for all values in the configuration, produce a config like:

```
/path/to/foo foo-value
/path/to/bar bar-value
...
```

The format of the path is the xpath expression; e.g.

```
snabb config get my-instance /path/to/foo
```

should print `foo-value`.

**Comment by mislavn** [comment]
@wingo would it be a problem to show the nodes which have default values also. So for an example:

```
root# snabb config get 46 /softwire-config/external-interface    
...
/path/to/ip 10.10.10.10;
/path/to/mac 12:12:12:12:12:12;
...
```
should have the MTU node regardless if it has the default value 1460:

```
root# snabb config get 46 /softwire-config/external-interface
...
/path/to/ip 10.10.10.10;
/path/to/mac 12:12:12:12:12:12;
/path/to/mtu 1460;
...
```
