### ISSUE TITLE
Ignore files produced by make snabb-lwaftr-doc

### ISSUE THREAD

**Issue by dpino** [Igalia/snabbswitch#84]
Running `make snabb-lwaftr-doc` within `program/snabb_lwaftr`, generates four documentation files in several formats (.md, .pdf, .html and .epub). As these are generated docs, they should not be tracked. Add a .gitignore file to remove them from the stage.

**Comment by kbara** [comment]
That would be good, yes.

**Comment by dpino** [comment]
Solved by PR #86
