### ISSUE TITLE
Integration of YANG alarms into snabb-softwire

### ISSUE THREAD

**Issue by dpino** [Igalia/snabbswitch#842]
Alarms are a mechanism for warning about errors in a system. When an error or a potential cause of trouble happens, an alarm is raised. Alarms inform about situations which usually can be corrected. But it's the network operator's responsibility to fix an alarm. Alarms are not self-healing.

To standardize the behaviour of alarms, https://datatracker.ietf.org/doc/draft-vallin-netmod-alarm-module/ has been proposed.

An example of an alarm in the lwAFTR is the inability of resolving the IP address of the internal and external interface next hop. When that happens, all the traffic routed to the lwAFTR is lost. However, there are other reasons why this could happen (problems in other elements of the network). In this situation, the lwAFTR could raise and alarm informing it could not resolve the IP address, and also provide information of how to fix that situation. Right now an error message is printed in stdout, but the message will be missed unless the operator is interacting directly with the lwAFTR on a terminal.

We want to integrate support of YANG alarms in the lwAFTR. To do we have identified 3 significant steps.

- [x] Add support for YANG alarms schema.
- [x] Integrate YANG alarms in snabb-softwire.yang.
- [x] Add support for YANG alarms RPC calls (purge-alarms, compress-alarms)

**Support YANG alarms schema**

After some additions, at this moment alarms schema can be parsed by Snabb's YANG library. It might be necessary to improve the YANG library if required.

**Integrate YANG alarms in YANG snabb-softwire**

YANG provides mechanisms to enable reusability. Keywords such as 'uses' or 'augments' allow to reuse definitions or extend a YANG module. However, there are no mechanism to compose or embed different YANG modules into a single module. What we propose is to import YANG alarms module from snabb-softwire. That will give us access to all the data types definitions. Then we will extend snabb-softwire replicating the necessary containers we would like to support. Initially, we will replicate the most basic alarms container definition.

**Add support for YANG alarms RPC calls**

Once snabb-softwire has been extended with alarms support, it will be possible to use `snabb config` to get, set, add alarms, likewise we do for other elements of snabb-softwire.

However, it will be necessary to add support for the RPC calls defined in YANG alarms. Ideally, what we would like to support is something like:

```lua
$ sudo ./snabb config purge-alarms <PID>
```

Snabb-config implement RPC calls such as get, set, add, etc. This RPC calls are defined in `snabb-config-leader-v1.yang`. We would like to extend this schema to add support for the RPC calls relative to alarms.  A possible way to implement this proposal would be:

1) When we start the leader, we start the leader with an extended version of `snabb-config-leader-v1.yang`. This extended YANG schema includes the alarms RPC calls.

2) The RPC calls would be eventually handled by the leader. For instance, RPC call `get-state` is handled by `Leader:foreign_rpc_get_state`.

3) Since `leader.lua` do not feature methods to handle the extra RPC calls, in addition with the extended schema, we will pass a handler object for the extra RPC calls. It would work as fallback mechanism. This is easy to implement using metatables:

Instead of:

```lua
function Leader:new (conf)
	local ret = setmetatable({}, {__index=Leader})
	...
end
```

```lua
local ret
if conf.rpc_handler then
	ret = setmetatable({}, {index = setmetatable(Leader, {index=conf.rpc_handler}})
else
	ret = setmetatable({}, {__index=Leader})
end
```

This main three subtasks address all the requirements necessary to integrate YANG alarms in the lwAFTR.

**Comment by plajjan** [comment]
I think there's a misunderstanding here. 

> YANG provides mechanisms to enable reusability. Keywords such as 'uses' or 'augments' allow to reuse definitions or extend a YANG module. However, there are no mechanism to compose or embed different YANG modules into a single module. What we propose is to import YANG alarms module from snabb-softwire. That will give us access to all the data types definitions. Then we will extend snabb-softwire replicating the necessary containers we would like to support. Initially, we will replicate the most basic alarms container definition.

Sentence number three worries me. You are not supposed to compose or embed different YANG modules. You are certainly not supposed to copy parts of a model into your own.

The point of having *one* alarm module is that it all looks the same. When something comes in with the ietf-alarms namespace I know what it is. If you just copy that model in under the snabb namespace I won't know how to deal with this in my NMS. I would have to implement for every vendor and that is exactly what we don't want.

I don't think you need to import the IETF alarm draft module into your own YANG module. You need to use the ietf alarm module from your code, i.e. the snabb lwaftr will have config / operation state in both the lwaftr yang module and in the ietf alarms draft module. That's perfectly natural and the intended way of using the model.

**Comment by plajjan** [comment]
BTW, there are actually ways of composing through the use of submodules but please, for the love of everything, do not go there ;) submodule scoping rules change between 1.0 and 1.1 and it's just a PITA to deal with for no real good reason. It's not a problem having many YANG models. For example, the Cisco IOS XR router I have running here have 331 capabilities, most of which are naturally YANG models. They actually use submodules too but nevermind that.

The most common reason I've seen for submodules is that a company wishes to publish a single model but internally the development happen in smaller organisational units that want to maintain control over their part, thus submodule comes in.

One can of course achieve the same thing through the use of a preprocessor to include yang structures from multiple sources into a single model. I would argue that would have actually been easier. Instead we now have a language that is burdened by this submodule complexity. Go look at the IETF mailing lists. submodule scoping rules is a PITA. I'm continuously evaluating models from our router vendors and submodule scoping rules is among the top contenders for source of issues. People don't understand them. Compilers don't understand them. Just avoid it. There's no reason to use them. &lt;/rant&gt; ;)

**Comment by svallin** [comment]
Hi!
I am the author of the module. Feel free to ping me directly if you have questions or want to discuss.
br Stefan

**Comment by dpino** [comment]
@plajjan This initial proposal is now outdated. After discussion, what we ended up doing was copying the parts we need of IETF alarms (the main containers: config, alarm-inventory, alarm-list, summary and shelved-alarms) into snabb-softwire-v2.yang. We import the alarms schema to preserve the original definitions of alarms data types, and use them from snabb-softwire-v2.yang through namespaces. As for the containers copied, they're a verbatim copy of the ones defined in the alarms schema. The alarms schema we are using is the last version of the proposed standard https://datatracker.ietf.org/doc/draft-vallin-netmod-alarm-module/

**Comment by plajjan** [comment]
@dpino it's unfortunate that this is what the discussion resulted in. May I ask if someone from TeraStream was present in that discussion? This is simply not correct use of YANG. I would like you to use the draft as is and thus just use the model straight up, not copy the content into your own model. If you want to make changes to the draft model then we can discuss this together with Stefan (@svallin). BTW, why did you delete his comment?

I am the consumer of these alarms and I implement the draft model. If you have all your nodes in your own namespace I won't be able to recognise them. Our code for handling alarms is generic, as it should be, and is thus using the draft namespace.

**Comment by dpino** [comment]
@plajjan I didn't recognize Stefan's as the author of alarms spec. I thought his comment was spam (like he was referring to the author of the module implementation). I will reestablish his comment if I can.

Let's discuss this over Slack. The alarms module is aimed to be delivered in the next release, beginning of October. We still have time to do changes.

**Comment by svallin** [comment]
Hi!
A few top level hints:
In a first iteration focus on the core part:
- wait with alarm shelving (filtering)
- the X.733 mapping is not needed until we meet old telco alarm managers, wait 

Do not forget the alarm quality requirements. These are almost more important than the YANG itself.

br Stefan

Stefan Vallin
stefan@wallan.se
+46705233262

**Comment by dpino** [comment]
@svallin thanks for the pointers. I have a question about the definition of the `severity` container in `filter-input` grouping used in `purge-alarms`:

```yang
container severity { 
   presence "Severity filter"; 
   choice sev-spec { 
       description 
           "Filter based on severity level."; 
       leaf below { 
           type severity; 
           description 
               "Severity less than this leaf."; 
       } 
       leaf is { 
           type severity; 
           description 
               "Severity level equal this leaf."; 
       } 
       leaf above { 
           type severity; 
           description 
               "Severity level higher than this leaf."; 
       } 
   } 
   description 
       "Filter based on severity."; 
}
```

It's a choice statement without cases. I'm not sure how to interpret that. Shouldn't be more like the definition of `older-than` (a choice statement with cases per age specification)? Something like:

```yang
container severity { 
   presence "Severity filter"; 
   choice sev-spec { 
       description 
           "Filter based on severity level."; 
       case below {
           leaf below {
               type severity;
               description
                  "Severity less than this leaf.";
           }
       }
       case is {
           leaf is {
               type severity;
               description
                  "Severity level equal this leaf.";
           }
       }
       case above {
           leaf above {
               type severity;
               description
                  "Severity level higher than this leaf.";
           }
       }
   } 
   description 
       "Filter based on severity."; 
}
```

**Comment by svallin** [comment]
Hi!
See section 7.9.2
As a shorthand, the "case" statement can be omitted if the branch
   contains a single "anydata", "anyxml", "choice", "container", "leaf",
   "list", or "leaf-list" statement.  In this case, the case node still
   exists in the schema tree, and its identifier is the same as the
   identifier of the child node. 


Stefan Vallin
stefan@wallan.se
+46705233262

**Comment by dpino** [comment]
Closing this ticket since the latest versions of the lwAFTR feature alarms support.
