### ISSUE TITLE
Fix errors compiling large binding tables

### ISSUE THREAD

**Issue by wingo** [Igalia/snabbswitch#856]
If you generate a binding table with 4 million entries and try to compile it, apparently LuaJIT runs out of memory.  Since we added the incremental parser, we shouldn't be seeing this, but maybe it's the simple fact of holding a big ol' string in memory.  If that's the case, we should use an off-heap string.  Anyway we need to investigate this issue and fix it.

Similarly, I understand that when querying the config leader for a large configuration, we build up a big string as well.  There we need to apply the same techniques.

Related to #692 / #654.  (At this point, now that we have switched to siphash the fix to #692 isn't a salt, but rather including the key in the compiled hash table, and having a separate key for each hash table.)

**Comment by dpino** [comment]
I'm no longer able to reproduce this error.

```bash
$ sudo ./snabb lwaftr generate-binding-table --output lwaftr-4m.conf \
   193.5.1.100 63496 fc00::100 fc00:1:2:3:4:5:0:7e 6
[edit lwaftr-4m.conf to add external-interface, internal-interface and instance information]
$ sudo ./snabb lwaftr run --conf lwaftr-4m.conf --name lwaftr --on-a-stick 83:00.0
lwaftr-4m.conf: loading compiled configuration from lwaftr-4m.o
lwaftr-4m.conf: compiled configuration is up to date.
Migrating instance 'test' to '83:00.0'
Warning: No NUMA memory affinity.
Pass --cpu to bind to a CPU and its NUMA node.
```

On running the lwAFTR, it's able to compile the configuration file and manage traffic, so it's working OK. I think this error got fixed due to https://github.com/Igalia/snabb/pull/935/commits/93b481889090446c1d7e81c947ccfc29d262a024

**Comment by dpino** [comment]
#829 is still valid though.

**Comment by wingo** [comment]
Neat.  How big of a binding table are you able to make?  Target is around 40M I think, so you can run a reasonable-sized national ISP with a single binding table.

**Comment by dpino** [comment]
Superseded by https://github.com/Igalia/snabb/issues/948
