### ISSUE TITLE
Design of configuration migration system

### ISSUE THREAD

**Issue by tsyesika** [Igalia/snabbswitch#876]
I've ended up writing a number of migrations over the course of my work the last few months and have noticed some problems with it's current design.

It currently works by each migration is responsible for it to upgrade it from the version it's migrating from, to the current config version. Every time the configuration changes every version's migration also needs to change and then subsequently be tested.

I think there is a better way which make the migrations much more reliable and easier to test. That is the way most database migrations work that I've come across. Each migration version is responsible only for upgrading from the previous configuration to the new version it is migrating to and the migrations are then chained together to perform a full migration. The UX would not change but rather behind the scenes it finds the specified migration, runs that and finds the next migration, rinse and repeat until there are no more migrations and it's at current.

I don't think this would be a large time investment but I do think it would make writing migrations easier and more reliable, as the migrations we're doing grows so does the amount of changes and testing you're doing. You really should just need to focus on the changes you're migrating from.

WDYT?

**Comment by wingo** [comment]
Sounds good to me, for what that's worth :)
