### ISSUE TITLE
Design for multiprocess support

### ISSUE THREAD

**Issue by tsyesika** [Igalia/snabbswitch#901]
This is an implementation of #819

This issue is to extend the lwaftr to support multiple instances of the lwaftr. These are defined in the schema specified in the PR #821. The lwaftr should be able to do three distinct additional things:

- When provided with a configuration with multiple instances, start those instances.
- Be able to spawn new additional instances whilst running in reconfigurable mode and destroy instances.
- Configure instance specific attributes without interrupting other instances.

These changes will also will need to update the translation layer so that multiple instances are provided in the `ietf-softwire` as well as be able to configure it from there also.

The state retrival parts will also need updating for the lwaftr as certain counters are now not just instance specific but are now agregate counters of all instances.

## Plan
  
I propose implementing this by upon the setup of the lwaftr it will spawn additional follower instances (lwaftr dataplanes) which will then talk to the one individual leader which will configure all of them. Each follower will be given the configuration which only includes its own configuration instance definition in the `instance` list.

The spawning of new instances will be performed by the leader using much the same process they were spawned upon initiation and removing instances will be performed by the `stop_app` functionality in the leader to follower API.

I'm thinking to make this easier to review a branch of the `lwaftr` will be made as a staging ground to merge PRs into as support is building up. That will PRs to be broken into smaller pieces e.g.

- Add support for starting multiple instances
- Add spawning new and destroying instances via the leader
- Update translation layer
- Update lwaftr's state code
  
WDYT (@wingo)?

**Comment by wingo** [comment]
Good ideas!

Just thinking aloud -- I wonder who should be the one spawning the various worker processes, the leader or the setup function?  Right now it's the setup function, but I don't know if that will be able to continue to be the case, given that the setup function doesn't keep track of the current state.  It's pretty much just a pure function.

I think we should change the type of the `setup` function that's passed to the leader.

Right now the setup function takes a configuration and returns an app graph.  We should change it to return a table mapping ID to app graph.  In that way we allow for multiple workers and can manage queue assignment etc in the setup function.  The leader would be responsible for spawning workers or killing them as needed.  WDYT?

**Comment by tsyesika** [comment]
I agree, I think that sounds like the right thing to do.

**Comment by dpino** [comment]
Fixed by #911, #939, #955 and #961
