### ISSUE TITLE
Under load IngressDropMonitor enters an infinite loop

### ISSUE THREAD

**Issue by U1F984** [Igalia/snabbswitch#913]
Running the lwaftr under heavy load or medium load without any warmup will trigger the IngressDropMonitor to flush the JIT and emit a warning like this:

```
1567272.0109992: warning: Dropped more than 100000 packets; flushing JIT to try to recover. See https://github.com/snabbco/snabb/blob/master/src/doc/performance-tuning.md for performance tuning tips.
```

While this is useful in some cases (e.g. traffic type changed so hot paths need to be re-jitted) under heavy load this causes it to loose another 100k packets before the JIT can react which in turn triggers the IngressDropMonitor again to flush JIT code.

<img width="1280" alt="packet lost count" src="https://user-images.githubusercontent.com/4466497/29605597-bdd6f79e-87eb-11e7-898a-6bbdd82073c4.png">

This could potentially be fixed by giving the program a grace period (e.g. one interval) before beginning to count the lost packets again or it should be a configurable option that one can turn off/change packet count/interval.

**Comment by dpino** [comment]
Fixed by #940.
