### ISSUE TITLE
Use large binding tables in Hydra jobsets

### ISSUE THREAD

**Issue by teknico** [Igalia/snabbswitch#946]
The lwAftr Hydra testing/CI [jobsets](https://hydra.snabb.co/project/igalia) are currently using small binding tables, which are not conducive to useful speed tests. To get the latter we need to use binding tables with many more softwires, ideally one million of them. Furthermore we have a requirement to reach 2MPPS per interface, with an average packet size of 550 bytes, while using a one million softwires binding table.

@dpino put together such a binding table, together with matching traffic data files, available as an [archive](https://people.igalia.com/dpino/lwaftr/lwaftr-datasets.tar.gz).

However the files are large, tens or hundreds of megabytes, and adding them to the Snabb repo is impractical.

Several approaches are possible:

- we could make the jobsets download the files from their URL: however that's complicated by the fact that the Snabb's Hydra instance runs jobsets in restricted mode, which severely limits access to external URLs;

- we could probably work around the restricted mode constraint by using Git's [Large File Storage](https://git-lfs.github.com) feature;

- or we could generate the files on the fly, at jobset execution time. We'd need to build and compile the binding table, and generate the traffic data files.

The latter approach is more versatile, even if more computing-intensive, so we'll explore that one.

**Comment by dpino** [comment]
Closing as we don't longer own Hydra infrastructure.
