### ISSUE TITLE
IPv4 ICMP does not work with VLAN tagging

### ISSUE THREAD

**Issue by andywingo** [Igalia/snabbswitch#99]

**Comment by kbara** [comment]
Solved by the combination of
https://github.com/Igalia/snabbswitch/pull/121
https://github.com/Igalia/snabbswitch/pull/124
as far as I can tell.

**Comment by andywingo** [comment]
Closing, then :)  Thank you @kbara!

**Comment by kbara** [comment]
These patches depend on https://github.com/Igalia/snabbswitch/pull/105 , btw.

**Comment by kbara** [comment]
Fixed in https://github.com/Igalia/snabbswitch/pull/131 for nutmeg.
