### ISSUE TITLE
Wrong order in list

### ISSUE THREAD

**Issue by calvincheng8** [Igalia/snabbswitch#995]
https://github.com/Igalia/snabb/blob/57041edddfcab149264f0cb1efc872480fdbf27e/src/lib/yang/snabb-softwire-v2.yang#L775

The `psid` leaf is part of the key to `softwire`. The key leaves in a list must appear on the top of list, also must be in the order specified by the key statement.

**Comment by tsyesika** [comment]
I had a look in the [YANG RFC](https://tools.ietf.org/html/rfc6020) and couldn't find anything about requiring the ordering of the leaf keys. Could you provide a reference to the section which specifies this, maybe I've just missed it.

**Comment by calvincheng8** [comment]
I was thinking of 
https://tools.ietf.org/html/rfc7950#page-85,

however this only specifies that the XML encoded data must have the keys in the order and appear first. So this is not a bug as long as the XML is encoded correctly.
